// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_nullity.djinni

#pragma once

namespace testsuite {

/** Used to pass around in tests that check nullity */
class DummyInterface {
public:
    virtual ~DummyInterface() {}
};

}  // namespace testsuite
