// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_constants.djinni

#pragma once

#include <cstdint>
#include <experimental/optional>
#include <string>

namespace testsuite {

struct FooConstants;

class FooConstantsInterface {
public:
    virtual ~FooConstantsInterface() {}

    static constexpr bool BOOL_CONSTANT = true;

    static constexpr int8_t I8_CONSTANT = 1;

    static constexpr int16_t I16_CONSTANT = 2;

    static constexpr int32_t I32_CONSTANT = 3;

    static constexpr int64_t I64_CONSTANT = 4;

    static constexpr float F32_CONSTANT = 5.0f;

    static constexpr double F64_CONSTANT = 6.0;

    static std::experimental::optional<int32_t> const OPTIONAL_INTEGER_CONSTANT;

    static std::string const STRING_CONSTANT;

    static FooConstants const OBJECT_CONSTANT;
};

}  // namespace testsuite
