// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_constants.djinni

#pragma once

#include "some_const_record.hpp"
#include <cstdint>
#include <experimental/optional>
#include <string>
#include <utility>

namespace testsuite {

struct FooConstants final {

    static constexpr bool BOOL_CONSTANT = true;

    static constexpr int8_t I8_CONSTANT = 1;

    static constexpr int16_t I16_CONSTANT = 2;

    static constexpr int32_t I32_CONSTANT = 3;

    static constexpr int64_t I64_CONSTANT = 4;

    static constexpr float F32_CONSTANT = 5.0f;

    static constexpr double F64_CONSTANT = 6.0;

    static std::string const STRING_CONSTANT;

    static std::experimental::optional<int32_t> const OPTIONAL_INTEGER_CONSTANT;

    static FooConstants const OBJECT_CONSTANT;

    static SomeConstRecord const SOME_RECORD;
    int32_t some_integer;
    std::string some_string;

    FooConstants(int32_t some_integer_,
                 std::string some_string_)
    : some_integer(std::move(some_integer_))
    , some_string(std::move(some_string_))
    {}
};

}  // namespace testsuite
