// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_constants.djinni

#include "foo_constants_interface.hpp"  // my header
#include "foo_constants.hpp"

namespace testsuite {

bool const FooConstantsInterface::BOOL_CONSTANT;

int8_t const FooConstantsInterface::I8_CONSTANT;

int16_t const FooConstantsInterface::I16_CONSTANT;

int32_t const FooConstantsInterface::I32_CONSTANT;

int64_t const FooConstantsInterface::I64_CONSTANT;

float const FooConstantsInterface::F32_CONSTANT;

double const FooConstantsInterface::F64_CONSTANT;

std::experimental::optional<int32_t> const FooConstantsInterface::OPTIONAL_INTEGER_CONSTANT = 1;

std::string const FooConstantsInterface::STRING_CONSTANT = {"another-string-constant"};

FooConstants const FooConstantsInterface::OBJECT_CONSTANT = FooConstants(
    FooConstantsInterface::I32_CONSTANT /* some_integer */ ,
    FooConstantsInterface::STRING_CONSTANT /* some_string */ );

}  // namespace testsuite
