// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_client_interface.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>
class FooExtensibleRecord; // Requiring extended class

namespace testsuite {

struct FooExtensibleRecordBase {
    int32_t number1;
    std::string string1;

    FooExtensibleRecordBase(int32_t number1,
                            std::string string1)
    : number1(std::move(number1))
    , string1(std::move(string1))
    {}

    virtual ~FooExtensibleRecordBase() = default;

protected:
    FooExtensibleRecordBase(const FooExtensibleRecordBase&) = default;
    FooExtensibleRecordBase(FooExtensibleRecordBase&&) = default;
    FooExtensibleRecordBase& operator=(const FooExtensibleRecordBase&) = default;
    FooExtensibleRecordBase& operator=(FooExtensibleRecordBase&&) = default;
};

}  // namespace testsuite
