// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from listeners.djinni

#pragma once

namespace testsuite {

class PyOnlyListener {
public:
    virtual ~PyOnlyListener() {}
};

}  // namespace testsuite
