// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

namespace testsuite {

/**
 * we need to test optional interface
 * this one will be used
 */
class SampleInterface {
public:
    virtual ~SampleInterface() {}
};

}  // namespace testsuite
