// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "NativeJavaOnlyListener.hpp"  // my header

namespace djinni_generated {

NativeJavaOnlyListener::NativeJavaOnlyListener() : ::djinni::JniInterface<::testsuite::JavaOnlyListener, NativeJavaOnlyListener>() {}

NativeJavaOnlyListener::~NativeJavaOnlyListener() = default;

NativeJavaOnlyListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeJavaOnlyListener::JavaProxy::~JavaProxy() = default;


}  // namespace djinni_generated
