// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include "djinni_support.hpp"
#include "opt_color_record.hpp"

namespace djinni_generated {

class NativeOptColorRecord final {
public:
    using CppType = ::testsuite::OptColorRecord;
    using JniType = jobject;

    using Boxed = NativeOptColorRecord;

    ~NativeOptColorRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeOptColorRecord();
    friend ::djinni::JniClass<NativeOptColorRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/OptColorRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lcom/dropbox/djinni/test/Color;)V") };
    const jfieldID field_mMyColor { ::djinni::jniGetFieldID(clazz.get(), "mMyColor", "Lcom/dropbox/djinni/test/Color;") };
};

}  // namespace djinni_generated
