// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#pragma once

#include "_varname_interface_.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeVarnameInterface final : ::djinni::JniInterface<::testsuite::VarnameInterface, NativeVarnameInterface> {
public:
    using CppType = std::shared_ptr<::testsuite::VarnameInterface>;
    using CppOptType = std::shared_ptr<::testsuite::VarnameInterface>;
    using JniType = jobject;

    using Boxed = NativeVarnameInterface;

    ~NativeVarnameInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVarnameInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVarnameInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVarnameInterface();
    friend ::djinni::JniClass<NativeVarnameInterface>;
    friend ::djinni::JniInterface<::testsuite::VarnameInterface, NativeVarnameInterface>;

};

}  // namespace djinni_generated
