// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#include "NativeMapRecord.hpp"  // my header
#include "HI64.hpp"
#include "HMap.hpp"
#include "HString.hpp"

namespace djinni { namespace jni {

jobject NativeMapRecord::toJava(JNIEnv* jniEnv, ::djinni::cpp::MapRecord c) {
    djinni::LocalRef<jobject> j_map(jniEnv, ::djinni::HMap<::djinni::HString, ::djinni::HI64>::toJava(jniEnv, c.map));
    const auto & data = djinni::JniClass<::djinni::jni::NativeMapRecord>::get();
    jobject r = jniEnv->NewObject(data.clazz.get(), data.jconstructor, j_map.get());
    djinni::jniExceptionCheck(jniEnv);
    return r;
}

::djinni::cpp::MapRecord NativeMapRecord::fromJava(JNIEnv* jniEnv, jobject j) {
    assert(j != nullptr);
    const auto & data = djinni::JniClass<::djinni::jni::NativeMapRecord>::get();
    return ::djinni::cpp::MapRecord(
        ::djinni::HMap<::djinni::HString, ::djinni::HI64>::fromJava(jniEnv, djinni::LocalRef<jobject>(jniEnv, jniEnv->GetObjectField(j, data.field_mMap)).get()));
}

} }  // namespace djinni::jni
