// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "djinni_support.hpp"
#include "interface_using_extended_record.hpp"

namespace djinni_generated {

class NativeInterfaceUsingExtendedRecord final : ::djinni::JniInterface<::testsuite::InterfaceUsingExtendedRecord, NativeInterfaceUsingExtendedRecord> {
public:
    using CppType = std::shared_ptr<::testsuite::InterfaceUsingExtendedRecord>;
    using CppOptType = std::shared_ptr<::testsuite::InterfaceUsingExtendedRecord>;
    using JniType = jobject;

    using Boxed = NativeInterfaceUsingExtendedRecord;

    ~NativeInterfaceUsingExtendedRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeInterfaceUsingExtendedRecord>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeInterfaceUsingExtendedRecord>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeInterfaceUsingExtendedRecord();
    friend ::djinni::JniClass<NativeInterfaceUsingExtendedRecord>;
    friend ::djinni::JniInterface<::testsuite::InterfaceUsingExtendedRecord, NativeInterfaceUsingExtendedRecord>;

};

}  // namespace djinni_generated
