// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

#pragma once

#include "djinni_support.hpp"
#include "record_with_duration_and_derivings.hpp"

namespace djinni_generated {

class NativeRecordWithDurationAndDerivings final {
public:
    using CppType = ::testsuite::RecordWithDurationAndDerivings;
    using JniType = jobject;

    using Boxed = NativeRecordWithDurationAndDerivings;

    ~NativeRecordWithDurationAndDerivings();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRecordWithDurationAndDerivings();
    friend ::djinni::JniClass<NativeRecordWithDurationAndDerivings>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/RecordWithDurationAndDerivings") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/time/Duration;)V") };
    const jfieldID field_mDt { ::djinni::jniGetFieldID(clazz.get(), "mDt", "Ljava/time/Duration;") };
};

}  // namespace djinni_generated
