// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#pragma once

#include "djinni_support.hpp"
#include "parcelable_optional_list.hpp"

namespace djinni_generated {

class NativeParcelableOptionalList final {
public:
    using CppType = ::testsuite::ParcelableOptionalList;
    using JniType = jobject;

    using Boxed = NativeParcelableOptionalList;

    ~NativeParcelableOptionalList();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeParcelableOptionalList();
    friend ::djinni::JniClass<NativeParcelableOptionalList>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/ParcelableOptionalList") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mOptionalSet { ::djinni::jniGetFieldID(clazz.get(), "mOptionalSet", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
