// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** Client interface */
public abstract class ClientInterface {
    /** Returns record of given string */
    @Nonnull
    public abstract ClientReturnedRecord getRecord(long recordId, @Nonnull String utf8string, @CheckForNull String misc);

    public abstract double identifierCheck(@Nonnull byte[] data, int r, long jret);

    @Nonnull
    public abstract String returnStr();

    @Nonnull
    public abstract String methTakingInterface(@CheckForNull ClientInterface i);

    @Nonnull
    public abstract String methTakingOptionalInterface(@CheckForNull ClientInterface i);
}
