// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** Record containing enum constant */
public class ConstantWithEnum {

    @Nonnull
    public static final ConstantEnum CONST_ENUM = ConstantEnum.SOME_VALUE;


    public ConstantWithEnum(
            ) {
    }

    @Override
    public String toString() {
        return "ConstantWithEnum{" +
        "}";
    }

}
