// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

package com.dropbox.djinni.test;

import java.util.Date;

public final class DateRecord {


    /*package*/ final Date mCreatedAt;

    public DateRecord(
            Date createdAt) {
        this.mCreatedAt = createdAt;
    }

    public Date getCreatedAt() {
        return mCreatedAt;
    }
}
