// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class EnumUsageRecord {


    /*package*/ final Color mE;

    /*package*/ final Color mO;

    /*package*/ final ArrayList<Color> mL;

    /*package*/ final HashSet<Color> mS;

    /*package*/ final HashMap<Color, Color> mM;

    public EnumUsageRecord(
            @Nonnull Color e,
            @CheckForNull Color o,
            @Nonnull ArrayList<Color> l,
            @Nonnull HashSet<Color> s,
            @Nonnull HashMap<Color, Color> m) {
        this.mE = e;
        this.mO = o;
        this.mL = l;
        this.mS = s;
        this.mM = m;
    }

    @Nonnull
    public Color getE() {
        return mE;
    }

    @CheckForNull
    public Color getO() {
        return mO;
    }

    @Nonnull
    public ArrayList<Color> getL() {
        return mL;
    }

    @Nonnull
    public HashSet<Color> getS() {
        return mS;
    }

    @Nonnull
    public HashMap<Color, Color> getM() {
        return mM;
    }

    @Override
    public String toString() {
        return "EnumUsageRecord{" +
                "mE=" + mE +
                "," + "mO=" + mO +
                "," + "mL=" + mL +
                "," + "mS=" + mS +
                "," + "mM=" + mM +
        "}";
    }

}
