// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** Extended record */
public class ExtendedRecord implements android.os.Parcelable {

    @Nonnull
    public static final ExtendedRecord EXTENDED_RECORD_CONST = new ExtendedRecord(
        true /* mFoo */ );


    /*package*/ final boolean mFoo;

    public ExtendedRecord(
            boolean foo) {
        this.mFoo = foo;
    }

    public boolean getFoo() {
        return mFoo;
    }

    @Override
    public String toString() {
        return "ExtendedRecord{" +
                "mFoo=" + mFoo +
        "}";
    }


    public static final android.os.Parcelable.Creator<ExtendedRecord> CREATOR
        = new android.os.Parcelable.Creator<ExtendedRecord>()
    {
        @Override
        public ExtendedRecord createFromParcel(android.os.Parcel in)
        {
            return new ExtendedRecord(in);
        }

        @Override
        public ExtendedRecord[] newArray(int size)
        {
            return new ExtendedRecord[size];
        }
    };

    public ExtendedRecord(android.os.Parcel in)
    {
        this.mFoo = in.readByte() != 0;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeByte(this.mFoo ? (byte)1 : 0);
    }

}
