// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashMap;

public final class MapListRecord {


    /*package*/ final ArrayList<HashMap<String, Long>> mMapList;

    public MapListRecord(
            ArrayList<HashMap<String, Long>> mapList) {
        this.mMapList = mapList;
    }

    public ArrayList<HashMap<String, Long>> getMapList() {
        return mMapList;
    }
}
