// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class NestedCollection {


    /*package*/ final ArrayList<HashSet<String>> mSetList;

    public NestedCollection(
            @Nonnull ArrayList<HashSet<String>> setList) {
        this.mSetList = setList;
    }

    @Nonnull
    public ArrayList<HashSet<String>> getSetList() {
        return mSetList;
    }

    @Override
    public String toString() {
        return "NestedCollection{" +
                "mSetList=" + mSetList +
        "}";
    }

}
