// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class ParcelableListSet implements android.os.Parcelable {


    /*package*/ final ArrayList<HashSet<String>> mListSet;

    public ParcelableListSet(
            @Nonnull ArrayList<HashSet<String>> listSet) {
        this.mListSet = listSet;
    }

    @Nonnull
    public ArrayList<HashSet<String>> getListSet() {
        return mListSet;
    }

    @Override
    public String toString() {
        return "ParcelableListSet{" +
                "mListSet=" + mListSet +
        "}";
    }


    public static final android.os.Parcelable.Creator<ParcelableListSet> CREATOR
        = new android.os.Parcelable.Creator<ParcelableListSet>() {
        @Override
        public ParcelableListSet createFromParcel(android.os.Parcel in) {
            return new ParcelableListSet(in);
        }

        @Override
        public ParcelableListSet[] newArray(int size) {
            return new ParcelableListSet[size];
        }
    };

    public ParcelableListSet(android.os.Parcel in) {
        this.mListSet = new ArrayList<HashSet<String>>();
        in.readList(this.mListSet, getClass().getClassLoader());
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeList(this.mListSet);
    }

}
