// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class ParcelableListMapSet implements android.os.Parcelable {


    /*package*/ final ArrayList<HashMap<String, HashSet<String>>> mListMapSet;

    public ParcelableListMapSet(
            @Nonnull ArrayList<HashMap<String, HashSet<String>>> listMapSet) {
        this.mListMapSet = listMapSet;
    }

    @Nonnull
    public ArrayList<HashMap<String, HashSet<String>>> getListMapSet() {
        return mListMapSet;
    }

    @Override
    public String toString() {
        return "ParcelableListMapSet{" +
                "mListMapSet=" + mListMapSet +
        "}";
    }


    public static final android.os.Parcelable.Creator<ParcelableListMapSet> CREATOR
        = new android.os.Parcelable.Creator<ParcelableListMapSet>() {
        @Override
        public ParcelableListMapSet createFromParcel(android.os.Parcel in) {
            return new ParcelableListMapSet(in);
        }

        @Override
        public ParcelableListMapSet[] newArray(int size) {
            return new ParcelableListMapSet[size];
        }
    };

    public ParcelableListMapSet(android.os.Parcel in) {
        this.mListMapSet = new ArrayList<HashMap<String, HashSet<String>>>();
        in.readList(this.mListMapSet, getClass().getClassLoader());
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeList(this.mListMapSet);
    }

}
