// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class ParcelableOptionalList implements android.os.Parcelable {


    /*package*/ final ArrayList<String> mOptionalSet;

    public ParcelableOptionalList(
            @CheckForNull ArrayList<String> optionalSet) {
        this.mOptionalSet = optionalSet;
    }

    @CheckForNull
    public ArrayList<String> getOptionalSet() {
        return mOptionalSet;
    }

    @Override
    public String toString() {
        return "ParcelableOptionalList{" +
                "mOptionalSet=" + mOptionalSet +
        "}";
    }


    public static final android.os.Parcelable.Creator<ParcelableOptionalList> CREATOR
        = new android.os.Parcelable.Creator<ParcelableOptionalList>() {
        @Override
        public ParcelableOptionalList createFromParcel(android.os.Parcel in) {
            return new ParcelableOptionalList(in);
        }

        @Override
        public ParcelableOptionalList[] newArray(int size) {
            return new ParcelableOptionalList[size];
        }
    };

    public ParcelableOptionalList(android.os.Parcel in) {
        if (in.readByte() == 0) {
            this.mOptionalSet = null;
        } else {
            this.mOptionalSet = new ArrayList<String>();
            in.readList(this.mOptionalSet, getClass().getClassLoader());
        }
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        if (this.mOptionalSet != null) {
            out.writeByte((byte)1);
            out.writeList(this.mOptionalSet);
        } else {
            out.writeByte((byte)0);
        }
    }

}
