// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class ParcelableOptionalSet implements android.os.Parcelable {


    /*package*/ final HashSet<String> mOptionalSet;

    public ParcelableOptionalSet(
            @CheckForNull HashSet<String> optionalSet) {
        this.mOptionalSet = optionalSet;
    }

    @CheckForNull
    public HashSet<String> getOptionalSet() {
        return mOptionalSet;
    }

    @Override
    public String toString() {
        return "ParcelableOptionalSet{" +
                "mOptionalSet=" + mOptionalSet +
        "}";
    }


    public static final android.os.Parcelable.Creator<ParcelableOptionalSet> CREATOR
        = new android.os.Parcelable.Creator<ParcelableOptionalSet>() {
        @Override
        public ParcelableOptionalSet createFromParcel(android.os.Parcel in) {
            return new ParcelableOptionalSet(in);
        }

        @Override
        public ParcelableOptionalSet[] newArray(int size) {
            return new ParcelableOptionalSet[size];
        }
    };

    public ParcelableOptionalSet(android.os.Parcel in) {
        if (in.readByte() == 0) {
            this.mOptionalSet = null;
        } else {
            ArrayList<String> mOptionalSetTemp = new ArrayList<String>();
            in.readList(mOptionalSetTemp, getClass().getClassLoader());
            this.mOptionalSet = new HashSet<String>(mOptionalSetTemp);
        }
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        if (this.mOptionalSet != null) {
            out.writeByte((byte)1);
            out.writeList(new ArrayList<String>(this.mOptionalSet));
        } else {
            out.writeByte((byte)0);
        }
    }

}
