// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

package com.dropbox.djinni.test;

import java.util.HashSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class SetRecord {


    /*package*/ final HashSet<String> mSet;

    /*package*/ final HashSet<Integer> mIset;

    public SetRecord(
            @Nonnull HashSet<String> set,
            @Nonnull HashSet<Integer> iset) {
        this.mSet = set;
        this.mIset = iset;
    }

    @Nonnull
    public HashSet<String> getSet() {
        return mSet;
    }

    @Nonnull
    public HashSet<Integer> getIset() {
        return mIset;
    }

    @Override
    public String toString() {
        return "SetRecord{" +
                "mSet=" + mSet +
                "," + "mIset=" + mIset +
        "}";
    }

}
