// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_inheritance.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class SubObjcJavaInterfaceInheritance extends BaseObjcJavaInterfaceInheritance {
    @Nonnull
    public abstract String subMethod();
}
