// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class WcharTestRec {


    /*package*/ final String mS;

    public WcharTestRec(
            @Nonnull String s) {
        this.mS = s;
    }

    @Nonnull
    public String getS() {
        return mS;
    }

    @Override
    public String toString() {
        return "WcharTestRec{" +
                "mS=" + mS +
        "}";
    }

}
