// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"
#include "item_list.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSItemList;

namespace djinni_generated {

struct ItemList
{
    using CppType = ::textsort::ItemList;
    using ObjcType = TXSItemList*;

    using Boxed = ItemList;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
