// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>


@interface TXSItemList : NSObject
- (id)initWithItemList:(TXSItemList *)itemList;
- (id)initWithItems:(NSArray *)items;

@property (nonatomic, readonly) NSArray *items;

@end
