// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"


@implementation TXSItemList

- (nonnull instancetype)initWithItems:(nonnull NSArray<NSString *> *)items
{
    if (self = [super init]) {
        _items = [items copy];
    }
    return self;
}

+ (nonnull instancetype)itemListWithItems:(nonnull NSArray<NSString *> *)items
{
    return [[self alloc] initWithItems:items];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<class, %@ : %p, dict, %@>", self.class, self, [[self toDict] description]];
}

- (NSDictionary *)toDict
{
    #define _djinni_hide_null_(_o_) ((_o_)?(_o_):([NSNull null]))
    
    return @{@"__class_name__": [self.class description], @"items": _djinni_hide_null_(self.items)};
}

@end
