// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>


@interface TXSItemList : NSObject

@property (nonatomic, readonly) NSMutableArray *items;

@end
