// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"
#include <utility>
#include <vector>


@implementation TXSItemList

- (id)initWithItemList:(TXSItemList *)itemList
{
    if (self = [super init]) {
        std::vector<NSString *> _itemsTempVector;
        _itemsTempVector.reserve([itemList.items count]);
        for (NSString *currentValue_0 in itemList.items) {
            NSString *copiedValue_0;
            copiedValue_0 = [currentValue_0 copy];
            _itemsTempVector.push_back(copiedValue_0);
        }
        _items = [NSArray arrayWithObjects:&_itemsTempVector[0] count:_itemsTempVector.size()];
    }
    return self;
}

- (id)initWithItems:(NSArray *)items
{
    if (self = [super init]) {
        _items = items;
    }
    return self;
}


@end
