// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativeTextboxListener.hpp"  // my header
#include "NativeItemList.hpp"

namespace djinni_generated {

NativeTextboxListener::NativeTextboxListener() : ::djinni::JniInterface<::textsort::TextboxListener, NativeTextboxListener>() {}

NativeTextboxListener::~NativeTextboxListener() = default;

NativeTextboxListener::JavaProxy::JavaProxy(JniType j) : JavaProxyCacheEntry(j) { }

NativeTextboxListener::JavaProxy::~JavaProxy() = default;

void NativeTextboxListener::JavaProxy::update(const ::textsort::ItemList & items)
{
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTextboxListener>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_update,
                           ::djinni_generated::NativeItemList::fromCpp(jniEnv, items).get());
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
