// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "sort_items.hpp"

namespace djinni_generated {

class NativeSortItems final : djinni::JniInterfaceCppExt<::textsort::SortItems> {
public:
    using CppType = std::shared_ptr<::textsort::SortItems>;
    using JniType = jobject;

    static jobject toJava(JNIEnv* jniEnv, std::shared_ptr<::textsort::SortItems> c) { return djinni::JniClass<NativeSortItems>::get()._toJava(jniEnv, c); }
    static std::shared_ptr<::textsort::SortItems> fromJava(JNIEnv* jniEnv, jobject j) { return djinni::JniClass<NativeSortItems>::get()._fromJava(jniEnv, j); }


private:
    NativeSortItems();
    friend class djinni::JniClass<NativeSortItems>;
};

}  // namespace djinni_generated
