// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativeTextboxResetListener.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeTextboxResetListener::NativeTextboxResetListener() : ::djinni::JniInterface<::textsort::TextboxResetListener, NativeTextboxResetListener>() {}

NativeTextboxResetListener::~NativeTextboxResetListener() = default;

NativeTextboxResetListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeTextboxResetListener::JavaProxy::~JavaProxy() = default;

void NativeTextboxResetListener::JavaProxy::reset(const std::string & c_text) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTextboxResetListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_reset,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_text)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
