// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "constants.hpp"
#import "DBConstants.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated { namespace objc {

struct Constants
{
    using CppType = ::djinni_generated::Constants;
    using ObjcType = DBConstants*;

    using Boxed = Constants;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} }  // namespace djinni_generated::objc
