// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#pragma once

#include <memory>

namespace testsuite {

struct VarnameRecord;

class VarnameInterface {
public:
    virtual ~VarnameInterface() {}

    virtual VarnameRecord _rmethod_(const VarnameRecord & _r_arg_) = 0;

    virtual std::shared_ptr<VarnameInterface> _imethod_(const std::shared_ptr<VarnameInterface> & _i_arg_) = 0;
};

}  // namespace testsuite
