// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "client_returned_record.hpp"
#include <cstdint>
#include <string>

namespace djinni { namespace cpp {

class ClientInterface {
public:
    virtual ~ClientInterface() {}

    /** Returns record of given string */
    virtual ClientReturnedRecord get_record(int64_t record_id, const std::string & utf8string) = 0;
};

} }  // namespace djinni::cpp
