// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "../../handwritten-src/cpp/optional.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace testsuite {

/** Record returned by a client */
struct ClientReturnedRecord final {
    int64_t record_id;
    std::string content;
    std::experimental::optional<std::string> misc;

    ClientReturnedRecord(int64_t record_id_,
                         std::string content_,
                         std::experimental::optional<std::string> misc_)
    : record_id(std::move(record_id_))
    , content(std::move(content_))
    , misc(std::move(misc_))
    {}
};

}  // namespace testsuite
