// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include <functional>

namespace djinni { namespace cpp {

enum class color : int {
    RED,
    ORANGE,
    YELLOW,
    GREEN,
    BLUE,
    /**
     * "It is customary to list indigo as a color lying between blue and violet, but it has
     * never seemed to me that indigo is worth the dignity of being considered a separate
     * color. To my eyes it seems merely deep blue." --Isaac Asimov
     */
    INDIGO,
    VIOLET,
};

} }  // namespace djinni::cpp

namespace std {

template <>
struct hash<::djinni::cpp::color> {
    size_t operator()(::djinni::cpp::color type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
