// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "project_export.hpp"
#include <memory>
#include <unordered_set>

namespace testsuite {

class Conflict;

class PROJECT_EXPORT ConflictUser {
public:
    virtual ~ConflictUser() {}

    virtual std::shared_ptr<::testsuite::Conflict> Conflict() = 0;

    virtual bool conflict_arg(const std::unordered_set<std::shared_ptr<::testsuite::Conflict>> & cs) = 0;
};

}  // namespace testsuite
