// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "constants.hpp"  // my header

namespace testsuite {

bool constexpr Constants::BOOL_CONSTANT;

int8_t constexpr Constants::I8_CONSTANT;

int16_t constexpr Constants::I16_CONSTANT;

int32_t constexpr Constants::I32_CONSTANT;

int64_t constexpr Constants::I64_CONSTANT;

float constexpr Constants::F32_CONSTANT;

double constexpr Constants::F64_CONSTANT;

std::experimental::optional<bool> const Constants::OPT_BOOL_CONSTANT = true;

std::experimental::optional<int8_t> const Constants::OPT_I8_CONSTANT = 1;

std::experimental::optional<int16_t> const Constants::OPT_I16_CONSTANT = 2;

std::experimental::optional<int32_t> const Constants::OPT_I32_CONSTANT = 3;

std::experimental::optional<int64_t> const Constants::OPT_I64_CONSTANT = 4;

std::experimental::optional<float> const Constants::OPT_F32_CONSTANT = 5.0;

std::experimental::optional<double> const Constants::OPT_F64_CONSTANT = 5.0;

std::string const Constants::STRING_CONSTANT = {"string-constant"};

std::experimental::optional<std::string> const Constants::OPT_STRING_CONSTANT = {"string-constant"};

ConstantRecord const Constants::OBJECT_CONSTANT = ConstantRecord(
    Constants::I32_CONSTANT /* some_integer */ ,
    Constants::STRING_CONSTANT /* some_string */ );

bool constexpr Constants::DUMMY;

}  // namespace testsuite
