// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "constants.hpp"  // my header

namespace testsuite {

std::string const Constants::STRING_CONSTANT = {"string-constant"};

std::experimental::optional<std::string> const Constants::OPT_STRING_CONSTANT = {"string-constant"};

ConstantRecord const Constants::OBJECT_CONSTANT = ConstantRecord(
    Constants::I32_CONSTANT /* some_integer */ ,
    Constants::STRING_CONSTANT /* some_string */ );

}  // namespace testsuite
