// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once

#include "../../handwritten-src/cpp/optional.hpp"
#include <cstdint>
#include <string>

namespace testsuite {

struct ConstantRecord;

/** Interface containing constants */
class ConstantsInterface {
public:
    virtual ~ConstantsInterface() {}

    /**
     * Defines the name of the JNI C++ proxy class. Used to convert a
     * C++ implemented object to a Java object when the type of the object being
     * converted is unknown to the JniInterface (see djinni_support.hpp).
     * 
     * The proxy class name is only used for converting Djinni interfaces that
     * are implemented in C++. Java implemented interfaces are converted differently.
     * However, the C++ class of an interface implemented in Java must still have a
     * jniProxyClassName method in order for Djinni's JniInterface::fromCpp method to compile.
     * 
     * @return The name of the class's associated JNI proxy class.
     * 
     * @see JniInterface in djinni_support.hpp
     */
    virtual const std::string jniProxyClassName() { return "com/dropbox/djinni/test/ConstantsInterface$CppProxy"; }

    /**
     * Defines the name of the Objective-C type for the class. Used to convert a
     * C++ object to an Objective-C object when the type of the object being
     * converted is unknown to the C++ wrapper cache (see DJICppWrapperCache+Private.hpp).
     * 
     * @return The name of the Objective C type associated with the class.
     * 
     * @see get_cpp_proxy function in DJICppWrapperCache+Private.hpp
     */
    virtual const std::string objcProxyClassName() { return "DBConstantsInterface"; }

    static bool const BOOL_CONSTANT;

    static int8_t const I8_CONSTANT;

    static int16_t const I16_CONSTANT;

    /** i32_constant has documentation. */
    static int32_t const I32_CONSTANT;

    /**
     * i64_constant has long documentation.
     * (Second line of multi-line documentation.
     *   Indented third line of multi-line documentation.)
     */
    static int64_t const I64_CONSTANT;

    static float const F32_CONSTANT;

    static double const F64_CONSTANT;

    static std::experimental::optional<bool> const OPT_BOOL_CONSTANT;

    static std::experimental::optional<int8_t> const OPT_I8_CONSTANT;

    /** opt_i16_constant has documentation. */
    static std::experimental::optional<int16_t> const OPT_I16_CONSTANT;

    static std::experimental::optional<int32_t> const OPT_I32_CONSTANT;

    static std::experimental::optional<int64_t> const OPT_I64_CONSTANT;

    /**
     * opt_f32_constant has long documentation.
     * (Second line of multi-line documentation.
     *   Indented third line of multi-line documentation.)
     */
    static std::experimental::optional<float> const OPT_F32_CONSTANT;

    static std::experimental::optional<double> const OPT_F64_CONSTANT;

    static std::string const STRING_CONSTANT;

    static std::experimental::optional<std::string> const OPT_STRING_CONSTANT;

    static ConstantRecord const OBJECT_CONSTANT;

    /**
     * No support for null optional constants
     * No support for optional constant records
     * No support for constant binary, list, set, map
     */
    virtual void dummy() = 0;
};

}  // namespace testsuite
