// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "color.hpp"
#include "project_export.hpp"
#include "record_with_derivings.hpp"
#include <utility>

/** This file tests YAML dumped by Djinni can be parsed back in */
struct PROJECT_EXPORT ExternRecordWithDerivings final {
    ::testsuite::RecordWithDerivings member;
    ::testsuite::color e;

    PROJECT_EXPORT friend bool operator==(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);
    PROJECT_EXPORT friend bool operator!=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);

    PROJECT_EXPORT friend bool operator<(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);
    PROJECT_EXPORT friend bool operator>(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);

    PROJECT_EXPORT friend bool operator<=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);
    PROJECT_EXPORT friend bool operator>=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);

    ExternRecordWithDerivings(::testsuite::RecordWithDerivings member_,
                              ::testsuite::color e_)
    : member(std::move(member_))
    , e(std::move(e_))
    {}
};
