// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "project_export.hpp"
#include "extended_record_base.hpp"  // my header
#include "../../handwritten-src/cpp/extended_record.hpp"

namespace testsuite {

PROJECT_EXPORT ExtendedRecord const ExtendedRecordBase::EXTENDED_RECORD_CONST = ExtendedRecord(
    true /* foo */ );

}  // namespace testsuite
