// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "project_export.hpp"
#include <utility>

namespace testsuite {

struct PROJECT_EXPORT ExtendedRecord; // Requiring extended class

/** Extended record */
struct PROJECT_EXPORT ExtendedRecordBase {

    static ExtendedRecord const EXTENDED_RECORD_CONST;
    bool foo;

    ExtendedRecordBase(bool foo_)
    : foo(std::move(foo_))
    {}

    virtual ~ExtendedRecordBase() = default;

protected:
    ExtendedRecordBase(const ExtendedRecordBase&) = default;
    ExtendedRecordBase(ExtendedRecordBase&&) = default;
    ExtendedRecordBase& operator=(const ExtendedRecordBase&) = default;
    ExtendedRecordBase& operator=(ExtendedRecordBase&&) = default;
};

}  // namespace testsuite
