// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

namespace testsuite {

/** Used for ObjC multiple inheritance tests */
class FirstListener {
public:
    virtual ~FirstListener() {}

    virtual void first() = 0;
};

}  // namespace testsuite
