// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

namespace testsuite {

struct ExtendedRecord;
struct RecordUsingExtendedRecord;

class InterfaceUsingExtendedRecord {
public:
    virtual ~InterfaceUsingExtendedRecord() {}

    static RecordUsingExtendedRecord const CR;

    virtual ExtendedRecord meth(const ExtendedRecord & er) = 0;
};

}  // namespace testsuite
