// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include "project_export.hpp"

namespace testsuite {

class PROJECT_EXPORT JavaOnlyListener {
public:
    virtual ~JavaOnlyListener() {}
};

}  // namespace testsuite
