// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#pragma once

#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

namespace testsuite {

struct ParcelableListSet final {
    std::vector<std::unordered_set<std::string>> list_set;

    ParcelableListSet(std::vector<std::unordered_set<std::string>> list_set_)
    : list_set(std::move(list_set_))
    {}
};

}  // namespace testsuite
