// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#pragma once

#include "project_export.hpp"
#include <cstdint>
#include <utility>
#include <vector>

namespace testsuite {

struct PROJECT_EXPORT PrimitiveList final {
    std::vector<int64_t> list;

    PrimitiveList(std::vector<int64_t> list_)
    : list(std::move(list_))
    {}
};

}  // namespace testsuite
