// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "record_using_extended_record.hpp"  // my header

namespace testsuite {

RecordUsingExtendedRecord const RecordUsingExtendedRecord::CR = RecordUsingExtendedRecord(
    ExtendedRecord(
        false /* foo */ ) /* er */ );

}  // namespace testsuite
