// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "project_export.hpp"

namespace testsuite {

/** Used for ObjC multiple inheritance tests */
class PROJECT_EXPORT SecondListener {
public:
    virtual ~SecondListener() {}

    virtual void second() = 0;
};

}  // namespace testsuite
