// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from listeners.djinni

#pragma once

namespace testsuite {

class SecondListener {
public:
    virtual ~SecondListener() {}

    virtual void second() = 0;
};

}  // namespace testsuite
