// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from token.djinni

#pragma once

#include <string>

class Token {
public:
    virtual ~Token() {}

    virtual std::string whoami() = 0;
};
