// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_token.djinni

#pragma once

#include "project_export.hpp"
#include <string>

namespace testsuite {

class PROJECT_EXPORT UserToken {
public:
    virtual ~UserToken() {}

    virtual std::string whoami() = 0;
};

}  // namespace testsuite
