// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "conflict_user.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__conflict_user.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperConflictUser final {
    DjinniWrapperConflictUser(std::shared_ptr<::testsuite::ConflictUser>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::ConflictUser> get(djinni::Handle<DjinniWrapperConflictUser> dw);
    static djinni::Handle<DjinniWrapperConflictUser> wrap(std::shared_ptr<::testsuite::ConflictUser> obj);

    const std::shared_ptr<::testsuite::ConflictUser> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
