// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_duplicate_file_creation.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "Foo_Callback2.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__Foo_Callback2.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperFooCallback2 final {
    DjinniWrapperFooCallback2(std::shared_ptr<::testsuite::FooCallback2>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::FooCallback2> get(djinni::Handle<DjinniWrapperFooCallback2> dw);
    static djinni::Handle<DjinniWrapperFooCallback2> wrap(std::shared_ptr<::testsuite::FooCallback2> obj);

    const std::shared_ptr<::testsuite::FooCallback2> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};

class FooCallback2PythonProxy final : public ::testsuite::FooCallback2 {
    public:
        explicit FooCallback2PythonProxy(DjinniObjectHandle * c_ptr);
        ~FooCallback2PythonProxy();
        DjinniObjectHandle * get_m_py_obj_handle();

        void methodA(const std::vector<::testsuite::FooRecord> & records);

        void methodB(const std::vector<::testsuite::FooRecord> & records);

    private:
        DjinniObjectHandle * m_py_obj_handle;
};
