// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniWrapperObjcOnlyListener;
void objc_only_listener___wrapper_dec_ref(struct DjinniWrapperObjcOnlyListener * dh);
void objc_only_listener___wrapper_add_ref(struct DjinniWrapperObjcOnlyListener * dh);
