// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "java_only_listener.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__java_only_listener.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperJavaOnlyListener final {
    DjinniWrapperJavaOnlyListener(std::shared_ptr<::testsuite::JavaOnlyListener>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::JavaOnlyListener> get(djinni::Handle<DjinniWrapperJavaOnlyListener> dw);
    static djinni::Handle<DjinniWrapperJavaOnlyListener> wrap(std::shared_ptr<::testsuite::JavaOnlyListener> obj);

    const std::shared_ptr<::testsuite::JavaOnlyListener> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
