// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_static.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "foo_static.hpp"

#include "cw__foo_static.hpp"
#include <chrono>
#include <experimental/optional>

std::shared_ptr<::testsuite::FooStatic> DjinniWrapperFooStatic::get(djinni::WrapperRef<DjinniWrapperFooStatic> dw) {
    if (dw) {
        return dw->wrapped_obj;
    }
    return nullptr;
}

void foo_static___wrapper_add_ref(DjinniWrapperFooStatic * dh) {
    dh->ref_count.fetch_add(1);
}
void foo_static___wrapper_dec_ref(DjinniWrapperFooStatic * dh) {
    const size_t ref = dh->ref_count.fetch_sub(1);
    if (ref == 1) {// value before sub is returned
        delete dh;
    }
}
djinni::Handle<DjinniWrapperFooStatic> DjinniWrapperFooStatic::wrap(std::shared_ptr<::testsuite::FooStatic> obj) {
    if (obj)
        return djinni::Handle<DjinniWrapperFooStatic>(new DjinniWrapperFooStatic{ std::move(obj) }, foo_static___wrapper_dec_ref);
    return nullptr;
}

DjinniString * cw__foo_static_update_static_messg_to(DjinniString * static_string) {
    std::unique_ptr<DjinniString> _static_string(static_string);
    try {
        return DjinniString::fromCpp(::testsuite::FooStatic::update_static_messg_to(DjinniString::toCpp(std::move(_static_string)))).release();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

DjinniString * cw__foo_static_get_static_messg() {
    try {
        return DjinniString::fromCpp(::testsuite::FooStatic::get_static_messg()).release();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

int32_t cw__foo_static_update_static_counter_by(int32_t plus) {
    try {
        return ::testsuite::FooStatic::update_static_counter_by(plus);
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

int32_t cw__foo_static_update_static_counter_to(int32_t init) {
    try {
        return ::testsuite::FooStatic::update_static_counter_to(init);
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

int32_t cw__foo_static_get_static_counter() {
    try {
        return ::testsuite::FooStatic::get_static_counter();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

uint64_t cw__foo_static_date_id(uint64_t d) {
    try {
        return DjinniDate::fromCpp(::testsuite::FooStatic::date_id(DjinniDate::toCpp(d)));
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

DjinniBoxedDate * cw__foo_static_opt_date_id(DjinniBoxedDate * od) {
    std::unique_ptr<DjinniBoxedDate> _od(od);
    try {
        return DjinniBoxedDate::fromCpp(::testsuite::FooStatic::opt_date_id(DjinniBoxedDate::toCpp(std::move(_od)))).release();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

DjinniBoxedI64 * cw__foo_static_opt_i64_id(DjinniBoxedI64 * od) {
    std::unique_ptr<DjinniBoxedI64> _od(od);
    try {
        return DjinniBoxedI64::fromCpp(::testsuite::FooStatic::opt_i64_id(DjinniBoxedI64::toCpp(std::move(_od)))).release();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}
