// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniWrapperListenerCaller;
void listener_caller___wrapper_dec_ref(struct DjinniWrapperListenerCaller * dh);
void listener_caller___wrapper_add_ref(struct DjinniWrapperListenerCaller * dh);

struct DjinniWrapperListenerCaller * cw__listener_caller_init(struct DjinniWrapperFirstListener * first_l, struct DjinniWrapperSecondListener * second_l);

void cw__listener_caller_callFirst(struct DjinniWrapperListenerCaller * djinni_this);

void cw__listener_caller_callSecond(struct DjinniWrapperListenerCaller * djinni_this);

