// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "first_listener.hpp"

#include "cw__first_listener.hpp"

static void(*s_py_callback_first_listener_first)(DjinniObjectHandle * );
static void(*s_py_callback_first_listener___delete)(DjinniObjectHandle * );

std::shared_ptr<::testsuite::FirstListener> DjinniWrapperFirstListener::get(djinni::WrapperRef<DjinniWrapperFirstListener> dw) {
    if (dw) {
        return dw->wrapped_obj;
    }
    return nullptr;
}

void first_listener___delete(DjinniObjectHandle * dh) {
    s_py_callback_first_listener___delete(dh);
}
void first_listener___wrapper_add_ref(DjinniWrapperFirstListener * dh) {
    dh->ref_count.fetch_add(1);
}
void first_listener___wrapper_dec_ref(DjinniWrapperFirstListener * dh) {
    const size_t ref = dh->ref_count.fetch_sub(1);
    if (ref == 1) {// value before sub is returned
        delete dh;
    }
}
djinni::Handle<DjinniWrapperFirstListener> DjinniWrapperFirstListener::wrap(std::shared_ptr<::testsuite::FirstListener> obj) {
    if (obj)
        return djinni::Handle<DjinniWrapperFirstListener>(new DjinniWrapperFirstListener{ std::move(obj) }, first_listener___wrapper_dec_ref);
    return nullptr;
}

DjinniWrapperFirstListener *  make_proxy_object_from_handle_cw__first_listener(DjinniObjectHandle * c_ptr) {
    return new DjinniWrapperFirstListener{std::make_shared<FirstListenerPythonProxy>(c_ptr)};
}

DjinniObjectHandle * get_handle_from_proxy_object_cw__first_listener(DjinniWrapperFirstListener * dw) {
    FirstListenerPythonProxy * cast_ptr = dynamic_cast<FirstListenerPythonProxy * >(dw->wrapped_obj.get());
    if (!cast_ptr) { return nullptr; }
    else return cast_ptr->get_m_py_obj_handle();
}

bool equal_handles_cw__first_listener(DjinniWrapperFirstListener * dw1, DjinniWrapperFirstListener * dw2) {
    return dw1->wrapped_obj == dw2->wrapped_obj;
}

DjinniObjectHandle * FirstListenerPythonProxy::get_m_py_obj_handle() {
    return m_py_obj_handle;
}

FirstListenerPythonProxy::FirstListenerPythonProxy(DjinniObjectHandle * c_ptr) : m_py_obj_handle(c_ptr) {}

FirstListenerPythonProxy::~FirstListenerPythonProxy() {
    s_py_callback_first_listener___delete(m_py_obj_handle);
}

void first_listener_add_callback_first(void(* ptr)(DjinniObjectHandle * )) {
    s_py_callback_first_listener_first = ptr;
}

void first_listener_add_callback___delete(void(* ptr)(DjinniObjectHandle * )) {
    s_py_callback_first_listener___delete = ptr;
}

void FirstListenerPythonProxy::first() {
    s_py_callback_first_listener_first(m_py_obj_handle);
    djinni::cw_throw_if_pending();
}
