// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_token.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "user_token.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__user_token.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperUserToken final {
    DjinniWrapperUserToken(std::shared_ptr<::testsuite::UserToken>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::UserToken> get(djinni::Handle<DjinniWrapperUserToken> dw);
    static djinni::Handle<DjinniWrapperUserToken> wrap(std::shared_ptr<::testsuite::UserToken> obj);

    const std::shared_ptr<::testsuite::UserToken> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
