// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "cpp_exception.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__cpp_exception.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperCppException final {
    DjinniWrapperCppException(std::shared_ptr<::testsuite::CppException>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::CppException> get(djinni::Handle<DjinniWrapperCppException> dw);
    static djinni::Handle<DjinniWrapperCppException> wrap(std::shared_ptr<::testsuite::CppException> obj);

    const std::shared_ptr<::testsuite::CppException> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
