// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

struct DjinniWrapperClientInterface;
void client_interface___delete(struct DjinniObjectHandle * djinni_this);
void client_interface___wrapper_dec_ref(struct DjinniWrapperClientInterface * dh);
void client_interface___wrapper_add_ref(struct DjinniWrapperClientInterface * dh);

struct DjinniWrapperClientInterface *  make_proxy_object_from_handle_cw__client_interface(struct DjinniObjectHandle * c_ptr);
struct DjinniObjectHandle * get_handle_from_proxy_object_cw__client_interface(struct DjinniWrapperClientInterface * dw);
bool equal_handles_cw__client_interface(struct DjinniWrapperClientInterface * dw1, struct DjinniWrapperClientInterface * dw2);

void client_interface_add_callback_get_record(struct DjinniRecordHandle *(* ptr)(struct DjinniObjectHandle * , int64_t, struct DjinniString *, struct DjinniString *));

void client_interface_add_callback_identifier_check(double(* ptr)(struct DjinniObjectHandle * , struct DjinniBinary *, int32_t, int64_t));

void client_interface_add_callback_return_str(struct DjinniString *(* ptr)(struct DjinniObjectHandle * ));

void client_interface_add_callback_meth_taking_interface(struct DjinniString *(* ptr)(struct DjinniObjectHandle * , struct DjinniWrapperClientInterface *));

void client_interface_add_callback_meth_taking_optional_interface(struct DjinniString *(* ptr)(struct DjinniObjectHandle * , struct DjinniWrapperClientInterface *));

void client_interface_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
