// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_client_interface.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "foo_client_interface.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__foo_client_interface.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperFooClientInterface final {
    DjinniWrapperFooClientInterface(std::shared_ptr<::testsuite::FooClientInterface>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::FooClientInterface> get(djinni::Handle<DjinniWrapperFooClientInterface> dw);
    static djinni::Handle<DjinniWrapperFooClientInterface> wrap(std::shared_ptr<::testsuite::FooClientInterface> obj);

    const std::shared_ptr<::testsuite::FooClientInterface> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
