// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "uses_single_language_listeners.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__uses_single_language_listeners.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperUsesSingleLanguageListeners final {
    DjinniWrapperUsesSingleLanguageListeners(std::shared_ptr<::testsuite::UsesSingleLanguageListeners>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::UsesSingleLanguageListeners> get(djinni::Handle<DjinniWrapperUsesSingleLanguageListeners> dw);
    static djinni::Handle<DjinniWrapperUsesSingleLanguageListeners> wrap(std::shared_ptr<::testsuite::UsesSingleLanguageListeners> obj);

    const std::shared_ptr<::testsuite::UsesSingleLanguageListeners> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
