// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdbool.h> // python_cdef_ignore
#include <stdint.h> // python_cdef_ignore

struct DjinniWrapperConstantsInterface;
void constants_interface___wrapper_dec_ref(struct DjinniWrapperConstantsInterface * dh);
void constants_interface___wrapper_add_ref(struct DjinniWrapperConstantsInterface * dh);

void cw__constants_interface_dummy(struct DjinniWrapperConstantsInterface * djinni_this);

