// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "objc_only_listener.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__objc_only_listener.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperObjcOnlyListener final {
    DjinniWrapperObjcOnlyListener(std::shared_ptr<::testsuite::ObjcOnlyListener>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::testsuite::ObjcOnlyListener> get(djinni::Handle<DjinniWrapperObjcOnlyListener> dw);
    static djinni::Handle<DjinniWrapperObjcOnlyListener> wrap(std::shared_ptr<::testsuite::ObjcOnlyListener> obj);

    const std::shared_ptr<::testsuite::ObjcOnlyListener> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
