// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_nullity.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "static_nullity_interface.hpp"

#include "cw__dummy_interface.hpp"
#include "cw__static_nullity_interface.hpp"
#include <experimental/optional>

std::shared_ptr<::testsuite::StaticNullityInterface> DjinniWrapperStaticNullityInterface::get(djinni::WrapperRef<DjinniWrapperStaticNullityInterface> dw) {
    if (dw) {
        return dw->wrapped_obj;
    }
    return nullptr;
}

void static_nullity_interface___wrapper_add_ref(DjinniWrapperStaticNullityInterface * dh) {
    dh->ref_count.fetch_add(1);
}
void static_nullity_interface___wrapper_dec_ref(DjinniWrapperStaticNullityInterface * dh) {
    const size_t ref = dh->ref_count.fetch_sub(1);
    if (ref == 1) {// value before sub is returned
        delete dh;
    }
}
djinni::Handle<DjinniWrapperStaticNullityInterface> DjinniWrapperStaticNullityInterface::wrap(std::shared_ptr<::testsuite::StaticNullityInterface> obj) {
    if (obj) 
        return djinni::Handle<DjinniWrapperStaticNullityInterface>(new DjinniWrapperStaticNullityInterface{ std::move(obj) }, static_nullity_interface___wrapper_dec_ref);
    return nullptr;
}

void cw__static_nullity_interface_non_null_parameters(DjinniWrapperDummyInterface * p1, DjinniWrapperDummyInterface * p2) {
    djinni::Handle<DjinniWrapperDummyInterface> _p1(p1, dummy_interface___wrapper_dec_ref);
    djinni::Handle<DjinniWrapperDummyInterface> _p2(p2, dummy_interface___wrapper_dec_ref);
    try { 
        ::testsuite::StaticNullityInterface::non_null_parameters(DjinniWrapperDummyInterface::get(std::move(_p1)), DjinniWrapperDummyInterface::get(std::move(_p2)));
    } CW_TRANSLATE_EXCEPTIONS_RETURN();
}

DjinniWrapperDummyInterface * cw__static_nullity_interface_non_null_return(bool should_return_null) {
    try { 
        return DjinniWrapperDummyInterface::wrap(std::move(::testsuite::StaticNullityInterface::non_null_return(should_return_null))).release();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}

void cw__static_nullity_interface_nullable_parameters(DjinniWrapperDummyInterface * p1, DjinniWrapperDummyInterface * p2) {
    djinni::Handle<DjinniWrapperDummyInterface> _p1(p1, dummy_interface___wrapper_dec_ref);
    djinni::Handle<DjinniWrapperDummyInterface> _p2(p2, dummy_interface___wrapper_dec_ref);
    try { 
        ::testsuite::StaticNullityInterface::nullable_parameters(DjinniWrapperDummyInterface::get(std::move(_p1)), DjinniWrapperDummyInterface::get(std::move(_p2)));
    } CW_TRANSLATE_EXCEPTIONS_RETURN();
}

DjinniWrapperDummyInterface * cw__static_nullity_interface_nullable_return(bool should_return_null) {
    try { 
        return DjinniWrapperDummyInterface::wrap(std::move(::testsuite::StaticNullityInterface::nullable_return(should_return_null))).release();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}
