// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "conflict_user.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__set_interface_Conflict.h"

#ifdef __cplusplus
}
#endif
struct DjinniSetInterfaceConflict {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::unordered_set<std::shared_ptr<::testsuite::Conflict>> & dc);
    static std::unordered_set<std::shared_ptr<::testsuite::Conflict>> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::experimental::optional<std::unordered_set<std::shared_ptr<::testsuite::Conflict>>> dc);
    static std::experimental::optional<std::unordered_set<std::shared_ptr<::testsuite::Conflict>>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
