// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "nested_collection.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__list_set_string.h"

#ifdef __cplusplus
}
#endif
struct DjinniListSetString {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::vector<std::unordered_set<std::string>> & dc);
    static std::vector<std::unordered_set<std::string>> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::experimental::optional<std::vector<std::unordered_set<std::string>>> dc);
    static std::experimental::optional<std::vector<std::unordered_set<std::string>>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
