// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdbool.h> // python_cdef_ignore
#include <stdint.h> // python_cdef_ignore

void map_string_int64_t___delete(struct DjinniObjectHandle *);
void optional_map_string_int64_t___delete(struct DjinniOptionalObjectHandle *);
void map_string_int64_t_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
void map_string_int64_t_add_callback__get_value(int64_t( * ptr)(struct DjinniObjectHandle *, struct DjinniString *));
void map_string_int64_t_add_callback__get_size(size_t( * ptr)(struct DjinniObjectHandle *));
void map_string_int64_t_add_callback__python_create(struct DjinniObjectHandle *( * ptr)());
void map_string_int64_t_add_callback__python_add(void( * ptr)(struct DjinniObjectHandle *, struct DjinniString *, int64_t));
void map_string_int64_t_add_callback__python_next(struct DjinniString *( * ptr)(struct DjinniObjectHandle *));
