// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "primitive_list.hpp"

#include "dh__list_int64_t.hpp"
#include "dh__primitive_list.hpp"

static void(*s_py_callback_list_int64_t___delete)(DjinniObjectHandle *);
void list_int64_t_add_callback___delete(void(* ptr)(DjinniObjectHandle *)) {
    s_py_callback_list_int64_t___delete = ptr;
}

void list_int64_t___delete(DjinniObjectHandle * drh) {
    s_py_callback_list_int64_t___delete(drh);
}
void optional_list_int64_t___delete(DjinniOptionalObjectHandle *  drh) {
    s_py_callback_list_int64_t___delete((DjinniObjectHandle *) drh);
}
static int64_t ( * s_py_callback_list_int64_t__get_elem)(DjinniObjectHandle *, size_t);

void list_int64_t_add_callback__get_elem(int64_t( * ptr)(DjinniObjectHandle *, size_t)) {
    s_py_callback_list_int64_t__get_elem = ptr;
}

static size_t ( * s_py_callback_list_int64_t__get_size)(DjinniObjectHandle *);

void list_int64_t_add_callback__get_size(size_t( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_list_int64_t__get_size = ptr;
}

static DjinniObjectHandle * ( * s_py_callback_list_int64_t__python_create)();

void list_int64_t_add_callback__python_create(DjinniObjectHandle *( * ptr)()) {
    s_py_callback_list_int64_t__python_create = ptr;
}

static void ( * s_py_callback_list_int64_t__python_add)(DjinniObjectHandle *, int64_t);

void list_int64_t_add_callback__python_add(void( * ptr)(DjinniObjectHandle *, int64_t)) {
    s_py_callback_list_int64_t__python_add = ptr;
}

djinni::Handle<DjinniObjectHandle> DjinniListInt64T::fromCpp(const std::vector<int64_t> & dc) {
    djinni::Handle<DjinniObjectHandle> _handle(s_py_callback_list_int64_t__python_create(), & list_int64_t___delete);
    size_t size = dc.size();
    for (int i = 0; i < size; i++) {
        s_py_callback_list_int64_t__python_add(_handle.get(), dc[i]);
    }

    return _handle;
}

std::vector<int64_t> DjinniListInt64T::toCpp(djinni::Handle<DjinniObjectHandle> dh) {
    std::vector<int64_t>_ret;
    size_t size = s_py_callback_list_int64_t__get_size(dh.get());
    _ret.reserve(size);

    for (int i = 0; i < size; i++) {
        _ret.push_back(s_py_callback_list_int64_t__get_elem(dh.get(), i));
    }

    return _ret;
}

djinni::Handle<DjinniOptionalObjectHandle> DjinniListInt64T::fromCpp(std::experimental::optional<std::vector<int64_t>> dc) {
    if (dc == std::experimental::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(std::move(DjinniListInt64T::fromCpp(std::move(* dc))), optional_list_int64_t___delete);
}

std::experimental::optional<std::vector<int64_t>>DjinniListInt64T::toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh) {
     if (dh) {
        return std::experimental::optional<std::vector<int64_t>>(DjinniListInt64T::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), list_int64_t___delete)));
    }
    return std::experimental::nullopt;
}

