// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

void map_int32_t_int32_t___delete(struct DjinniObjectHandle *);
void optional_map_int32_t_int32_t___delete(struct DjinniOptionalObjectHandle *);
void map_int32_t_int32_t_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
void map_int32_t_int32_t_add_callback__get_value(int32_t( * ptr)(struct DjinniObjectHandle *, int32_t));
void map_int32_t_int32_t_add_callback__get_size(size_t( * ptr)(struct DjinniObjectHandle *));
void map_int32_t_int32_t_add_callback__python_create(struct DjinniObjectHandle *( * ptr)());
void map_int32_t_int32_t_add_callback__python_add(void( * ptr)(struct DjinniObjectHandle *, int32_t, int32_t));
void map_int32_t_int32_t_add_callback__python_next(int32_t( * ptr)(struct DjinniObjectHandle *));
