// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "record_with_derivings.hpp"

#include "dh__record_with_derivings.hpp"

static void(*s_py_callback_record_with_derivings___delete)(DjinniRecordHandle * );
void record_with_derivings_add_callback___delete(void(* ptr)(DjinniRecordHandle * )) {
    s_py_callback_record_with_derivings___delete = ptr;
}

void record_with_derivings___delete(DjinniRecordHandle * drh) {
    s_py_callback_record_with_derivings___delete(drh);
}
void optional_record_with_derivings___delete(DjinniOptionalRecordHandle * drh) {
    s_py_callback_record_with_derivings___delete((DjinniRecordHandle *) drh); // can't static cast, find better way
}
static int32_t ( * s_py_callback_record_with_derivings_get_record_with_derivings_f1)(DjinniRecordHandle *);

void record_with_derivings_add_callback_get_record_with_derivings_f1(int32_t( * ptr)(DjinniRecordHandle *)) {
    s_py_callback_record_with_derivings_get_record_with_derivings_f1 = ptr;
}

static DjinniString * ( * s_py_callback_record_with_derivings_get_record_with_derivings_f2)(DjinniRecordHandle *);

void record_with_derivings_add_callback_get_record_with_derivings_f2(DjinniString *( * ptr)(DjinniRecordHandle *)) {
    s_py_callback_record_with_derivings_get_record_with_derivings_f2 = ptr;
}

static DjinniRecordHandle * ( * s_py_callback_record_with_derivings_python_create_record_with_derivings)(int32_t,DjinniString *);

void record_with_derivings_add_callback_python_create_record_with_derivings(DjinniRecordHandle *( * ptr)(int32_t,DjinniString *)) {
    s_py_callback_record_with_derivings_python_create_record_with_derivings = ptr;
}

djinni::Handle<DjinniRecordHandle> DjinniRecordWithDerivings::fromCpp(const ::testsuite::RecordWithDerivings& dr) {
    auto  _field_key2 = DjinniString::fromCpp(dr.key2);

    djinni::Handle<DjinniRecordHandle> _aux(
        s_py_callback_record_with_derivings_python_create_record_with_derivings(
            dr.key1,
            _field_key2.release()),
        record_with_derivings___delete);
    return _aux;
}

::testsuite::RecordWithDerivings DjinniRecordWithDerivings::toCpp(djinni::Handle<DjinniRecordHandle> dh) {
    std::unique_ptr<DjinniString> _field_key2(s_py_callback_record_with_derivings_get_record_with_derivings_f2(dh.get()));

    auto _aux = ::testsuite::RecordWithDerivings(
        s_py_callback_record_with_derivings_get_record_with_derivings_f1(dh.get()),
        DjinniString::toCpp(std::move( _field_key2)));
    return _aux;
}

djinni::Handle<DjinniOptionalRecordHandle> DjinniRecordWithDerivings::fromCpp(std::experimental::optional<::testsuite::RecordWithDerivings> dc) {
    if (dc == std::experimental::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(std::move(DjinniRecordWithDerivings::fromCpp(std::move(* dc))), optional_record_with_derivings___delete);
}

std::experimental::optional<::testsuite::RecordWithDerivings>DjinniRecordWithDerivings::toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh) {
     if (dh) {
        return std::experimental::optional<::testsuite::RecordWithDerivings>(DjinniRecordWithDerivings::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), record_with_derivings___delete)));
    }
    return std::experimental::nullopt;
}

