// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "map_list_record.hpp"

#include "dh__list_map_string_int64_t.hpp"
#include "dh__map_list_record.hpp"
#include "dh__map_string_int64_t.hpp"

static void(*s_py_callback_map_list_record___delete)(DjinniRecordHandle * );
void map_list_record_add_callback___delete(void(* ptr)(DjinniRecordHandle * )) {
    s_py_callback_map_list_record___delete = ptr;
}

void map_list_record___delete(DjinniRecordHandle * drh) {
    s_py_callback_map_list_record___delete(drh);
}
void optional_map_list_record___delete(DjinniOptionalRecordHandle * drh) {
    s_py_callback_map_list_record___delete((DjinniRecordHandle *) drh); // can't static cast, find better way
}
static DjinniObjectHandle * ( * s_py_callback_map_list_record_get_map_list_record_f1)(DjinniRecordHandle *);

void map_list_record_add_callback_get_map_list_record_f1(DjinniObjectHandle *( * ptr)(DjinniRecordHandle *)) {
    s_py_callback_map_list_record_get_map_list_record_f1 = ptr;
}

static DjinniRecordHandle * ( * s_py_callback_map_list_record_python_create_map_list_record)(DjinniObjectHandle *);

void map_list_record_add_callback_python_create_map_list_record(DjinniRecordHandle *( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_map_list_record_python_create_map_list_record = ptr;
}

djinni::Handle<DjinniRecordHandle> DjinniMapListRecord::fromCpp(const ::testsuite::MapListRecord& dr) {
    auto  _field_map_list = DjinniListMapStringInt64T::fromCpp(dr.map_list);

    djinni::Handle<DjinniRecordHandle> _aux(
        s_py_callback_map_list_record_python_create_map_list_record(
            _field_map_list.release()),
        map_list_record___delete);
    return _aux;
}

::testsuite::MapListRecord DjinniMapListRecord::toCpp(djinni::Handle<DjinniRecordHandle> dh) {
    djinni::Handle<DjinniObjectHandle> _field_map_list(s_py_callback_map_list_record_get_map_list_record_f1(dh.get()), list_map_string_int64_t___delete);

    auto _aux = ::testsuite::MapListRecord(
        DjinniListMapStringInt64T::toCpp(std::move( _field_map_list)));
    return _aux;
}

djinni::Handle<DjinniOptionalRecordHandle> DjinniMapListRecord::fromCpp(std::experimental::optional<::testsuite::MapListRecord> dc) {
    if (dc == std::experimental::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(std::move(DjinniMapListRecord::fromCpp(std::move(* dc))), optional_map_list_record___delete);
}

std::experimental::optional<::testsuite::MapListRecord>DjinniMapListRecord::toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh) {
     if (dh) {
        return std::experimental::optional<::testsuite::MapListRecord>(DjinniMapListRecord::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), map_list_record___delete)));
    }
    return std::experimental::nullopt;
}

