// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_containers.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "foo_containers_record.hpp"

#include "dh__foo_containers_record.hpp"
#include "dh__foo_some_other_record.hpp"
#include "dh__list_binary.hpp"
#include "dh__list_date.hpp"
#include "dh__list_int32_t.hpp"
#include "dh__list_list_string.hpp"
#include "dh__list_optional_binary.hpp"
#include "dh__list_record_foo_some_other_record.hpp"
#include "dh__list_string.hpp"
#include "dh__map_boxed_int32_t_set_string.hpp"
#include "dh__map_int8_t_list_date.hpp"
#include "dh__map_int8_t_set_string.hpp"
#include "dh__map_optional_string_optional_string.hpp"
#include "dh__map_string_int32_t.hpp"
#include "dh__map_string_string.hpp"
#include "dh__set_optional_string.hpp"
#include "dh__set_string.hpp"
#include <chrono>
#include <experimental/optional>
#include <vector>

static void(*s_py_callback_list_list_string___delete)(DjinniObjectHandle *);
void list_list_string_add_callback___delete(void(* ptr)(DjinniObjectHandle *)) {
    s_py_callback_list_list_string___delete = ptr;
}

void list_list_string___delete(DjinniObjectHandle * drh) {
    s_py_callback_list_list_string___delete(drh);
}
void optional_list_list_string___delete(DjinniOptionalObjectHandle *  drh) {
    s_py_callback_list_list_string___delete((DjinniObjectHandle *) drh);
}
static DjinniObjectHandle * ( * s_py_callback_list_list_string__get_elem)(DjinniObjectHandle *, size_t);

void list_list_string_add_callback__get_elem(DjinniObjectHandle *( * ptr)(DjinniObjectHandle *, size_t)) {
    s_py_callback_list_list_string__get_elem = ptr;
}

static size_t ( * s_py_callback_list_list_string__get_size)(DjinniObjectHandle *);

void list_list_string_add_callback__get_size(size_t( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_list_list_string__get_size = ptr;
}

static DjinniObjectHandle * ( * s_py_callback_list_list_string__python_create)();

void list_list_string_add_callback__python_create(DjinniObjectHandle *( * ptr)()) {
    s_py_callback_list_list_string__python_create = ptr;
}

static void ( * s_py_callback_list_list_string__python_add)(DjinniObjectHandle *, DjinniObjectHandle *);

void list_list_string_add_callback__python_add(void( * ptr)(DjinniObjectHandle *, DjinniObjectHandle *)) {
    s_py_callback_list_list_string__python_add = ptr;
}

djinni::Handle<DjinniObjectHandle> DjinniListListString::fromCpp(const std::vector<std::vector<std::string>> & dc) {
    djinni::Handle<DjinniObjectHandle> _handle(s_py_callback_list_list_string__python_create(), & list_list_string___delete);
    size_t size = dc.size();
    for (int i = 0; i < size; i++) {
        auto _el = DjinniListString::fromCpp(dc[i]);
        s_py_callback_list_list_string__python_add(_handle.get(), _el.release());
    }

    return _handle;
}

std::vector<std::vector<std::string>> DjinniListListString::toCpp(djinni::Handle<DjinniObjectHandle> dh) {
    std::vector<std::vector<std::string>>_ret;
    size_t size = s_py_callback_list_list_string__get_size(dh.get());
    _ret.reserve(size);

    for (int i = 0; i < size; i++) {
        _ret.push_back(DjinniListString::toCpp(std::move(djinni::Handle<DjinniObjectHandle>(s_py_callback_list_list_string__get_elem(dh.get(), i), list_string___delete))));
    }

    return _ret;
}

djinni::Handle<DjinniOptionalObjectHandle> DjinniListListString::fromCpp(std::experimental::optional<std::vector<std::vector<std::string>>> dc) {
    if (dc == std::experimental::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(std::move(DjinniListListString::fromCpp(std::move(* dc))), optional_list_list_string___delete);
}

std::experimental::optional<std::vector<std::vector<std::string>>>DjinniListListString::toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh) {
     if (dh) {
        return std::experimental::optional<std::vector<std::vector<std::string>>>(DjinniListListString::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), list_list_string___delete)));
    }
    return std::experimental::nullopt;
}

