// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

struct DjinniConstantRecord;
void constant_record___delete(struct DjinniRecordHandle * );
void optional_constant_record___delete(struct DjinniOptionalRecordHandle * );
void constant_record_add_callback_get_constant_record_f1(int32_t( * ptr)(struct DjinniRecordHandle *));
void constant_record_add_callback_get_constant_record_f2(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void constant_record_add_callback_python_create_constant_record(struct DjinniRecordHandle *( * ptr)(int32_t,struct DjinniString *));
void constant_record_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
