// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "nested_collection.hpp"

#include "dh__list_set_string.hpp"
#include "dh__nested_collection.hpp"
#include "dh__set_string.hpp"

static void(*s_py_callback_nested_collection___delete)(DjinniRecordHandle * );
void nested_collection_add_callback___delete(void(* ptr)(DjinniRecordHandle * )) {
    s_py_callback_nested_collection___delete = ptr;
}

void nested_collection___delete(DjinniRecordHandle * drh) {
    s_py_callback_nested_collection___delete(drh);
}
void optional_nested_collection___delete(DjinniOptionalRecordHandle * drh) {
    s_py_callback_nested_collection___delete((DjinniRecordHandle *) drh); // can't static cast, find better way
}
static DjinniObjectHandle * ( * s_py_callback_nested_collection_get_nested_collection_f1)(DjinniRecordHandle *);

void nested_collection_add_callback_get_nested_collection_f1(DjinniObjectHandle *( * ptr)(DjinniRecordHandle *)) {
    s_py_callback_nested_collection_get_nested_collection_f1 = ptr;
}

static DjinniRecordHandle * ( * s_py_callback_nested_collection_python_create_nested_collection)(DjinniObjectHandle *);

void nested_collection_add_callback_python_create_nested_collection(DjinniRecordHandle *( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_nested_collection_python_create_nested_collection = ptr;
}

djinni::Handle<DjinniRecordHandle> DjinniNestedCollection::fromCpp(const ::testsuite::NestedCollection& dr) {
    auto  _field_set_list = DjinniListSetString::fromCpp(dr.set_list);

    djinni::Handle<DjinniRecordHandle> _aux(
        s_py_callback_nested_collection_python_create_nested_collection(
            _field_set_list.release()),
        nested_collection___delete);
    return _aux;
}

::testsuite::NestedCollection DjinniNestedCollection::toCpp(djinni::Handle<DjinniRecordHandle> dh) {
    djinni::Handle<DjinniObjectHandle> _field_set_list(s_py_callback_nested_collection_get_nested_collection_f1(dh.get()), list_set_string___delete);

    auto _aux = ::testsuite::NestedCollection(
        DjinniListSetString::toCpp(std::move( _field_set_list)));
    return _aux;
}

djinni::Handle<DjinniOptionalRecordHandle> DjinniNestedCollection::fromCpp(std::experimental::optional<::testsuite::NestedCollection> dc) {
    if (dc == std::experimental::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(std::move(DjinniNestedCollection::fromCpp(std::move(* dc))), optional_nested_collection___delete);
}

std::experimental::optional<::testsuite::NestedCollection>DjinniNestedCollection::toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh) {
     if (dh) {
        return std::experimental::optional<::testsuite::NestedCollection>(DjinniNestedCollection::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), nested_collection___delete)));
    }
    return std::experimental::nullopt;
}

