// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "test_helpers.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__map_string_int64_t.h"

#ifdef __cplusplus
}
#endif
struct DjinniMapStringInt64T {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::unordered_map<std::string, int64_t> & dc);
    static std::unordered_map<std::string, int64_t> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::experimental::optional<std::unordered_map<std::string, int64_t>> dc);
    static std::experimental::optional<std::unordered_map<std::string, int64_t>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
