// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from foo_containers.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

void map_boxed_int32_t_set_string___delete(struct DjinniObjectHandle *);
void optional_map_boxed_int32_t_set_string___delete(struct DjinniOptionalObjectHandle *);
void map_boxed_int32_t_set_string_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
void map_boxed_int32_t_set_string_add_callback__get_value(struct DjinniObjectHandle *( * ptr)(struct DjinniObjectHandle *, struct DjinniBoxedI32 *));
void map_boxed_int32_t_set_string_add_callback__get_size(size_t( * ptr)(struct DjinniObjectHandle *));
void map_boxed_int32_t_set_string_add_callback__python_create(struct DjinniObjectHandle *( * ptr)());
void map_boxed_int32_t_set_string_add_callback__python_add(void( * ptr)(struct DjinniObjectHandle *, struct DjinniBoxedI32 *, struct DjinniObjectHandle *));
void map_boxed_int32_t_set_string_add_callback__python_next(struct DjinniBoxedI32 *( * ptr)(struct DjinniObjectHandle *));
