# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from test.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyRecord
from PyCFFIlib_cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class EmptyRecord:
    """
     Empty record
     (Second line of multi-line documentation.
       Indented third line of multi-line documentation.)
    """

    c_data_set = MultiSet()

    @staticmethod
    def check_c_data_set_empty():
        assert len(EmptyRecord.c_data_set) == 0


    def __init__(self):
        pass

