# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from map.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyObject, CPyObject, CPyObjectProxy, CPyPrimitive, CPyRecord, CPyString

from dh__list_map_string_int64_t import ListMapStringInt64THelper
from dh__map_string_int64_t import MapStringInt64THelper
from dh__map_string_int64_t import MapStringInt64TProxy
from PyCFFIlib_cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class MapListRecord:
    c_data_set = MultiSet()

    @staticmethod
    def check_c_data_set_empty():
        assert len(MapListRecord.c_data_set) == 0
        ListMapStringInt64THelper.check_c_data_set_empty()


    def __init__(self, map_list):
        self.map_list = map_list

