# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from single_language_interfaces.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files


from abc import ABCMeta, abstractmethod
from future.utils import with_metaclass
from PyCFFIlib_cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class ObjcOnlyListener(with_metaclass(ABCMeta)):

