# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from user_token.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyString

from abc import ABCMeta, abstractmethod
from future.utils import with_metaclass
from PyCFFIlib_cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class UserToken(with_metaclass(ABCMeta)):
    @abstractmethod
    def whoami(self):
        raise NotImplementedError


class UserTokenCppProxy(UserToken):
    def __init__(self, proxy):
        self._is_cpp_proxy = True
        self._cpp_impl = proxy
    def __del__(self):
        if not lib:
            return
        lib.user_token___wrapper_dec_ref(self._cpp_impl)

    def whoami(self):
        _ret_c = lib.cw__user_token_whoami(self._cpp_impl)
        CPyException.toPyCheckAndRaise(_ret_c)
        _ret = CPyString.toPy(_ret_c)
        assert _ret is not None
        return _ret

class UserTokenHelper:
    c_data_set = MultiSet()
    @staticmethod
    def toPy(obj):
        if obj == ffi.NULL:
            return None
        return UserTokenCppProxy(obj)

