// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "sort_items.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__sort_items.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperSortItems final {
    DjinniWrapperSortItems(std::shared_ptr<::textsort::SortItems>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::textsort::SortItems> get(djinni::Handle<DjinniWrapperSortItems> dw);
    static djinni::Handle<DjinniWrapperSortItems> wrap(std::shared_ptr<::textsort::SortItems> obj);

    const std::shared_ptr<::textsort::SortItems> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
