// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "sort_order.hpp"

int32_t int32_from_enum_sort_order(std::experimental::optional<::textsort::sort_order> e) {
    if (e) {
        return static_cast<int32_t>(* e);
    }
    return -1; // -1 to signal null boxed enum
}

int32_t int32_from_enum_sort_order(::textsort::sort_order e) {
    return static_cast<int32_t>(e);
}
std::experimental::optional<::textsort::sort_order> get_boxed_enum_sort_order_from_int32(int32_t e) {
    if (e == -1) { // to signal null enum
        return std::experimental::nullopt;
    }
    return std::experimental::optional<::textsort::sort_order>(static_cast<::textsort::sort_order>(e));
}
