// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ enum SortOrder {
    ASCENDING,
    DESCENDING,
    RANDOM,
    ;
}
