// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

#import "DBAssortedPrimitives.h"
#include "assorted_primitives.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBAssortedPrimitives;

namespace djinni_generated {

struct AssortedPrimitives
{
    using CppType = ::testsuite::AssortedPrimitives;
    using ObjcType = DBAssortedPrimitives*;

    using Boxed = AssortedPrimitives;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
