// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from inttypes.djinni

#import <Foundation/Foundation.h>

@interface DBAssortedIntegers : NSObject
- (nonnull id)initWithEight:(int8_t)eight
                    sixteen:(int16_t)sixteen
                  thirtytwo:(int32_t)thirtytwo
                  sixtyfour:(int64_t)sixtyfour
                     oEight:(nullable NSNumber *)oEight
                   oSixteen:(nullable NSNumber *)oSixteen
                 oThirtytwo:(nullable NSNumber *)oThirtytwo
                 oSixtyfour:(nullable NSNumber *)oSixtyfour;

@property (nonatomic, readonly) int8_t eight;

@property (nonatomic, readonly) int16_t sixteen;

@property (nonatomic, readonly) int32_t thirtytwo;

@property (nonatomic, readonly) int64_t sixtyfour;

@property (nonatomic, readonly, nullable) NSNumber * oEight;

@property (nonatomic, readonly, nullable) NSNumber * oSixteen;

@property (nonatomic, readonly, nullable) NSNumber * oThirtytwo;

@property (nonatomic, readonly, nullable) NSNumber * oSixtyfour;

@end
