// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstantRecord.h"
#import <Foundation/Foundation.h>

/** Record containing constants */
__attribute__((visibility ("default")))
@interface DBConstants : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)constants;

+ (NSNumber * __nullable)optBoolConstant;
+ (NSNumber * __nullable)optI8Constant;
/** opt_i16_constant has documentation. */
+ (NSNumber * __nullable)optI16Constant;
+ (NSNumber * __nullable)optI32Constant;
+ (NSNumber * __nullable)optI64Constant;
/**
 * opt_f32_constant has long documentation.
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
+ (NSNumber * __nullable)optF32Constant;
+ (NSNumber * __nullable)optF64Constant;
+ (DBConstantRecord * __nonnull)objectConstant;
@end

/** bool_constant has documentation. */
__attribute__((visibility ("default")))
extern BOOL const DBConstantsBoolConstant;
__attribute__((visibility ("default")))
extern int8_t const DBConstantsI8Constant;
__attribute__((visibility ("default")))
extern int16_t const DBConstantsI16Constant;
__attribute__((visibility ("default")))
extern int32_t const DBConstantsI32Constant;
__attribute__((visibility ("default")))
extern int64_t const DBConstantsI64Constant;
__attribute__((visibility ("default")))
extern float const DBConstantsF32Constant;
/**
 * f64_constant has long documentation.
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
__attribute__((visibility ("default")))
extern double const DBConstantsF64Constant;
__attribute__((visibility ("default")))
extern NSString * __nonnull const DBConstantsStringConstant;
__attribute__((visibility ("default")))
extern NSString * __nullable const DBConstantsOptStringConstant;
/**
 * No support for null optional constants
 * No support for optional constant records
 * No support for constant binary, list, set, map
 */
__attribute__((visibility ("default")))
extern BOOL const DBConstantsDummy;
