// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstantRecord.h"
#import <Foundation/Foundation.h>

/** Record containing constants */
@interface DBConstants : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)constants;

@end

/** bool_constant has documentation. */
extern BOOL const DBConstantsBoolConstant;
extern int8_t const DBConstantsI8Constant;
extern int16_t const DBConstantsI16Constant;
extern int32_t const DBConstantsI32Constant;
extern int64_t const DBConstantsI64Constant;
extern float const DBConstantsF32Constant;
/**
 * f64_constant has long documentation.
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
extern double const DBConstantsF64Constant;
extern NSNumber * __nullable const DBConstantsOptBoolConstant;
extern NSNumber * __nullable const DBConstantsOptI8Constant;
extern NSNumber * __nullable const DBConstantsOptI16Constant;
extern NSNumber * __nullable const DBConstantsOptI32Constant;
extern NSNumber * __nullable const DBConstantsOptI64Constant;
extern NSNumber * __nullable const DBConstantsOptF32Constant;
extern NSNumber * __nullable const DBConstantsOptF64Constant;
extern NSString * __nonnull const DBConstantsStringConstant;
extern NSString * __nullable const DBConstantsOptStringConstant;
extern DBConstantRecord * __nonnull const DBConstantsObjectConstant;
/**
 * No support for null optional constants
 * No support for optional constant records
 * No support for constant binary, list, set, map
 */
extern BOOL const DBConstantsDummy;
