// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#import "DBColorTranslator+Private.h"
#import <Foundation/Foundation.h>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@implementation DBColorTranslator

+ (DBColor)cppColorToObjcColor:(color)color
{
    return static_cast<DBColor>(color);
}

+ (color)objcColorToCppColor:(DBColor)color
{
    return static_cast<enum color>(color);
}

@end
