// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstants.h"
#import <Foundation/Foundation.h>

@interface DBConstants : NSObject
- (nonnull instancetype)initWithSomeInteger:(int32_t)someInteger
                                 someString:(nonnull NSString *)someString;
+ (nonnull instancetype)constantsWithSomeInteger:(int32_t)someInteger
                                      someString:(nonnull NSString *)someString;

@property (nonatomic, readonly) int32_t someInteger;

@property (nonatomic, readonly, nonnull) NSString * someString;

@end

extern BOOL const DBConstantsBoolConstant;
extern int8_t const DBConstantsI8Constant;
extern int16_t const DBConstantsI16Constant;
extern int32_t const DBConstantsI32Constant;
extern int64_t const DBConstantsI64Constant;
extern float const DBConstantsF32Constant;
extern double const DBConstantsF64Constant;
extern NSString * __nonnull const DBConstantsStringConstant;
extern NSNumber * __nullable const DBConstantsOptionalIntegerConstant;
extern DBConstants * __nonnull const DBConstantsObjectConstant;
