// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import <Foundation/Foundation.h>
@class DBConflict;


@interface DBConflictUser : NSObject

- (nullable DBConflict *)Conflict;

- (BOOL)conflictArg:(nonnull NSSet<DBConflict *> *)cs;

@end
