// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#import "DBColor.h"
#include "color.hpp"
#import <Foundation/Foundation.h>

@interface DBColorTranslator : NSObject

+ (DBColor)cppColorToObjcColor:(color)color;
+ (color)objcColorToCppColor:(DBColor)color;

@end
