// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstantsInterface.h"


BOOL const DBConstantsInterfaceBoolConstant = YES;

int8_t const DBConstantsInterfaceI8Constant = 1;

int16_t const DBConstantsInterfaceI16Constant = 2;

int32_t const DBConstantsInterfaceI32Constant = 3;

int64_t const DBConstantsInterfaceI64Constant = 4;

float const DBConstantsInterfaceF32Constant = 5.0f;

double const DBConstantsInterfaceF64Constant = 5.0;

NSString * __nonnull const DBConstantsInterfaceStringConstant = @"string-constant";

NSString * __nullable const DBConstantsInterfaceOptStringConstant = @"string-constant";
