// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#import "DBConstantWithEnum.h"


@implementation DBConstantWithEnum

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)constantWithEnum
{
    return [[self alloc] init];
}

+ (DBConstantEnum)constEnum
{
    static DBConstantEnum const s_constEnum = DBConstantEnumSomeValue;
    return s_constEnum;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
