// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstantRecord.h"
#import <Foundation/Foundation.h>

extern BOOL const DBConstantsInterfaceBoolConstant;
extern int8_t const DBConstantsInterfaceI8Constant;
extern int16_t const DBConstantsInterfaceI16Constant;
/** i32_constant has documentation. */
extern int32_t const DBConstantsInterfaceI32Constant;
/**
 * i64_constant has long documentation.
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
extern int64_t const DBConstantsInterfaceI64Constant;
extern float const DBConstantsInterfaceF32Constant;
extern double const DBConstantsInterfaceF64Constant;
extern NSString * __nonnull const DBConstantsInterfaceStringConstant;
extern NSString * __nullable const DBConstantsInterfaceOptStringConstant;

/** Interface containing constants */
@interface DBConstantsInterface : NSObject

/**
 * No support for null optional constants
 * No support for optional constant records
 * No support for constant binary, list, set, map
 */
- (void)dummy;

+ (NSNumber * __nullable)optBoolConstant;
+ (NSNumber * __nullable)optI8Constant;
/** opt_i16_constant has documentation. */
+ (NSNumber * __nullable)optI16Constant;
+ (NSNumber * __nullable)optI32Constant;
+ (NSNumber * __nullable)optI64Constant;
/**
 * opt_f32_constant has long documentation.
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
+ (NSNumber * __nullable)optF32Constant;
+ (NSNumber * __nullable)optF64Constant;
+ (DBConstantRecord * __nonnull)objectConstant;
@end
