// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstants.h"
#include "constants.hpp"
#import <Foundation/Foundation.h>

@interface DBConstants ()

- (id)initWithCppConstants:(const Constants &)constants;
- (Constants)cppConstants;

@end
