// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstants+Private.h"
#import "DBConstants+Private.h"
#import "DJIDate.h"
#import "DJIMarshal+Private.h"
#import <Foundation/Foundation.h>
#include <cassert>
#include <utility>
#include <vector>

namespace djinni_generated {

auto Constants::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    int32_t some_integer = ::djinni::I32::toCpp(obj.someInteger);
    std::string some_string = ::djinni::String::toCpp(obj.someString);
    return ::Constants(
        some_integer,
        some_string);
}

auto Constants::fromCpp(const CppType& cpp) -> ObjcType
{
    int32_t someInteger = ::djinni::I32::fromCpp(cpp.some_integer);
    NSString *someString = ::djinni::String::fromCpp(cpp.some_string);
    return [[DBConstants alloc]
        initWithSomeInteger:someInteger
        someString:someString];
}

}  // namespace djinni_generated
