// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#import <Foundation/Foundation.h>

@interface DBDateRecord : NSObject
- (nonnull instancetype)initWithCreatedAt:(nonnull NSDate *)createdAt;
+ (nonnull instancetype)dateRecordWithCreatedAt:(nonnull NSDate *)createdAt;

@property (nonatomic, readonly, nonnull) NSDate * createdAt;

- (NSComparisonResult)compare:(nonnull DBDateRecord *)other;

@end
