// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#import <Foundation/Foundation.h>

@interface DBDateRecord : NSObject
- (id)initWithDateRecord:(DBDateRecord *)dateRecord;
- (id)initWithCreatedAt:(NSDate *)createdAt;

@property (nonatomic, readonly) NSDate * createdAt;

@end

