// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#import "DBDateRecord.h"
#include "date_record.hpp"
#import <Foundation/Foundation.h>

@interface DBDateRecord ()

- (id)initWithCppDateRecord:(const DateRecord &)dateRecord;
- (DateRecord)cppDateRecord;

@end
