// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import <Foundation/Foundation.h>

@interface DBEmptyRecord : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)emptyRecord;

@end
