// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#include "extern_interface_1.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBExternInterface1;

namespace djinni_generated {

class ExternInterface1
{
public:
    using CppType = std::shared_ptr<::ExternInterface1>;
    using CppOptType = std::shared_ptr<::ExternInterface1>;
    using ObjcType = DBExternInterface1*;

    using Boxed = ExternInterface1;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

