// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#import "DBClientInterface.h"
#import "DBClientReturnedRecord.h"
#import <Foundation/Foundation.h>


__attribute__((visibility ("default")))
@interface DBExternInterface1 : NSObject

- (nonnull DBClientReturnedRecord *)foo:(nullable id<DBClientInterface>)i;

@end
