// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#include "flag_roundtrip.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBFlagRoundtrip;

namespace djinni_generated {

class FlagRoundtrip
{
public:
    using CppType = std::shared_ptr<::testsuite::FlagRoundtrip>;
    using CppOptType = std::shared_ptr<::testsuite::FlagRoundtrip>;
    using ObjcType = DBFlagRoundtrip*;

    using Boxed = FlagRoundtrip;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

