// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#import "DBMapListRecord.h"
#include <utility>
#include <vector>


@implementation DBMapListRecord

- (id)initWithMapListRecord:(DBMapListRecord *)mapListRecord
{
    if (self = [super init]) {
        std::vector<NSDictionary *> _mapListTempVector;
        _mapListTempVector.reserve([mapListRecord.mapList count]);
        for (NSDictionary *currentValue_0 in mapListRecord.mapList) {
            NSDictionary *copiedValue_0;
            std::vector<NSString *> copiedValue_0TempKeyVector;
            copiedValue_0TempKeyVector.reserve([currentValue_0 count]);
            std::vector<NSNumber *> copiedValue_0TempValueVector;
            copiedValue_0TempValueVector.reserve([currentValue_0 count]);
            for (NSString *key_1 in currentValue_0) {
                NSNumber *copiedValue_1;
                copiedValue_0TempKeyVector.push_back(key_1);
                NSNumber *value_1 = [currentValue_0 objectForKey:key_1];
                copiedValue_1 = value_1;
                copiedValue_0TempValueVector.push_back(copiedValue_1);
            }
            copiedValue_0 = [NSDictionary dictionaryWithObjects:&copiedValue_0TempValueVector[0] forKeys:&copiedValue_0TempKeyVector[0] count:[currentValue_0 count]];
            _mapListTempVector.push_back(copiedValue_0);
        }
        _mapList = [NSArray arrayWithObjects:&_mapListTempVector[0] count:_mapListTempVector.size()];
    }
    return self;
}

- (id)initWithMapList:(NSArray *)mapList
{
    if (self = [super init]) {
        _mapList = mapList;
    }
    return self;
}


@end
