// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#import <Foundation/Foundation.h>


@interface DBMapListRecord : NSObject

@property (nonatomic, readonly) NSMutableArray *mapList;

@end
