// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#import "DBMapListRecord+Private.h"
#import "DJIDate.h"
#import "DJIMarshal+Private.h"
#import <Foundation/Foundation.h>
#include <cassert>
#include <utility>
#include <vector>

namespace djinni_generated {

auto MapListRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni::Map<::djinni::String, ::djinni::I64>>::toCpp(obj.mapList)};
}

auto MapListRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBMapListRecord alloc] initWithMapList:(::djinni::List<::djinni::Map<::djinni::String, ::djinni::I64>>::fromCpp(cpp.map_list))];
}

}  // namespace djinni_generated
