// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#import <Foundation/Foundation.h>

@interface DBMapRecord : NSObject
- (nonnull id)initWithMap:(nonnull NSDictionary *)map;

@property (nonatomic, readonly, nonnull) NSDictionary * map;

@end
