// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#import "DBMapRecord.h"


@implementation DBMapRecord

- (id)initWithMap:(nonnull NSDictionary *)map
{
    if (self = [super init]) {
        _map = map;
    }
    return self;
}


@end
