// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#import <Foundation/Foundation.h>


@interface DBNestedCollection : NSObject

@property (nonatomic, readonly) NSMutableArray *setList;

@end
