// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#import "DBNestedCollection.h"


@implementation DBNestedCollection

- (nonnull instancetype)initWithSetList:(nonnull NSArray<NSSet<NSString *> *> *)setList
{
    if (self = [super init]) {
        _setList = [setList copy];
    }
    return self;
}

+ (nonnull instancetype)nestedCollectionWithSetList:(nonnull NSArray<NSSet<NSString *> *> *)setList
{
    return [[self alloc] initWithSetList:setList];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p: dict, %@>", self.class, self, [[self toDict] description]];
}

- (NSDictionary *)toDict
{
    #define _djinni_hide_null_(_o_) ((_o_)?(_o_):([NSNull null]))
    
    return @{@"__class_name__": [self.class description], @"setList": _djinni_hide_null_(self.setList)};
}

@end
