// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import <Foundation/Foundation.h>

@interface DBOptionalSet : NSObject
- (nonnull instancetype)initWithOptionalSet:(nullable NSSet<NSString *> *)optionalSet;
+ (nonnull instancetype)optionalSetWithOptionalSet:(nullable NSSet<NSString *> *)optionalSet;

@property (nonatomic, readonly, nullable) NSSet<NSString *> * optionalSet;

@end
