// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#import "DBOptColorRecord.h"
#include "opt_color_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBOptColorRecord;

namespace djinni_generated {

struct OptColorRecord
{
    using CppType = ::testsuite::OptColorRecord;
    using ObjcType = DBOptColorRecord*;

    using Boxed = OptColorRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
