// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import <Foundation/Foundation.h>

@interface DBParcelablePrimitives : NSObject
- (nonnull instancetype)initWithB:(BOOL)b
                            eight:(int8_t)eight
                          sixteen:(int16_t)sixteen
                        thirtytwo:(int32_t)thirtytwo
                        sixtyfour:(int64_t)sixtyfour
                       fthirtytwo:(float)fthirtytwo
                       fsixtyfour:(double)fsixtyfour
                                s:(nonnull NSString *)s
                                d:(nonnull NSDate *)d
                               oB:(nullable NSNumber *)oB
                           oEight:(nullable NSNumber *)oEight
                         oSixteen:(nullable NSNumber *)oSixteen
                       oThirtytwo:(nullable NSNumber *)oThirtytwo
                       oSixtyfour:(nullable NSNumber *)oSixtyfour
                      oFthirtytwo:(nullable NSNumber *)oFthirtytwo
                      oFsixtyfour:(nullable NSNumber *)oFsixtyfour
                               oS:(nullable NSString *)oS
                               oD:(nullable NSDate *)oD;
+ (nonnull instancetype)parcelablePrimitivesWithB:(BOOL)b
                                            eight:(int8_t)eight
                                          sixteen:(int16_t)sixteen
                                        thirtytwo:(int32_t)thirtytwo
                                        sixtyfour:(int64_t)sixtyfour
                                       fthirtytwo:(float)fthirtytwo
                                       fsixtyfour:(double)fsixtyfour
                                                s:(nonnull NSString *)s
                                                d:(nonnull NSDate *)d
                                               oB:(nullable NSNumber *)oB
                                           oEight:(nullable NSNumber *)oEight
                                         oSixteen:(nullable NSNumber *)oSixteen
                                       oThirtytwo:(nullable NSNumber *)oThirtytwo
                                       oSixtyfour:(nullable NSNumber *)oSixtyfour
                                      oFthirtytwo:(nullable NSNumber *)oFthirtytwo
                                      oFsixtyfour:(nullable NSNumber *)oFsixtyfour
                                               oS:(nullable NSString *)oS
                                               oD:(nullable NSDate *)oD;

@property (nonatomic, readonly) BOOL b;

@property (nonatomic, readonly) int8_t eight;

@property (nonatomic, readonly) int16_t sixteen;

@property (nonatomic, readonly) int32_t thirtytwo;

@property (nonatomic, readonly) int64_t sixtyfour;

@property (nonatomic, readonly) float fthirtytwo;

@property (nonatomic, readonly) double fsixtyfour;

@property (nonatomic, readonly, nonnull) NSString * s;

@property (nonatomic, readonly, nonnull) NSDate * d;

@property (nonatomic, readonly, nullable) NSNumber * oB;

@property (nonatomic, readonly, nullable) NSNumber * oEight;

@property (nonatomic, readonly, nullable) NSNumber * oSixteen;

@property (nonatomic, readonly, nullable) NSNumber * oThirtytwo;

@property (nonatomic, readonly, nullable) NSNumber * oSixtyfour;

@property (nonatomic, readonly, nullable) NSNumber * oFthirtytwo;

@property (nonatomic, readonly, nullable) NSNumber * oFsixtyfour;

@property (nonatomic, readonly, nullable) NSString * oS;

@property (nonatomic, readonly, nullable) NSDate * oD;

@end
