// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import "DBParcelableListMapSet.h"


@implementation DBParcelableListMapSet

- (nonnull instancetype)initWithListMapSet:(nonnull NSArray<NSDictionary<NSString *, NSSet<NSString *> *> *> *)listMapSet
{
    if (self = [super init]) {
        _listMapSet = [listMapSet copy];
    }
    return self;
}

+ (nonnull instancetype)parcelableListMapSetWithListMapSet:(nonnull NSArray<NSDictionary<NSString *, NSSet<NSString *> *> *> *)listMapSet
{
    return [(DBParcelableListMapSet*)[self alloc] initWithListMapSet:listMapSet];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p listMapSet:%@>", self.class, (void *)self, self.listMapSet];
}

@end
