// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import <Foundation/Foundation.h>

@interface DBParcelableList : NSObject
- (nonnull instancetype)initWithL:(nonnull NSArray<NSString *> *)l;
+ (nonnull instancetype)parcelableListWithL:(nonnull NSArray<NSString *> *)l;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * l;

@end
