// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import "DBParcelableMapSet.h"


@implementation DBParcelableMapSet

- (nonnull instancetype)initWithMapSet:(nonnull NSDictionary<NSString *, NSSet<NSString *> *> *)mapSet
{
    if (self = [super init]) {
        _mapSet = [mapSet copy];
    }
    return self;
}

+ (nonnull instancetype)parcelableMapSetWithMapSet:(nonnull NSDictionary<NSString *, NSSet<NSString *> *> *)mapSet
{
    return [(DBParcelableMapSet*)[self alloc] initWithMapSet:mapSet];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p mapSet:%@>", self.class, (void *)self, self.mapSet];
}

@end
