// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import "DBParcelableOptionalSet.h"


@implementation DBParcelableOptionalSet

- (nonnull instancetype)initWithOptionalSet:(nullable NSSet<NSString *> *)optionalSet
{
    if (self = [super init]) {
        _optionalSet = [optionalSet copy];
    }
    return self;
}

+ (nonnull instancetype)parcelableOptionalSetWithOptionalSet:(nullable NSSet<NSString *> *)optionalSet
{
    return [(DBParcelableOptionalSet*)[self alloc] initWithOptionalSet:optionalSet];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p optionalSet:%@>", self.class, (void *)self, self.optionalSet];
}

@end
