// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#import "DBPrimitiveList.h"
#include "primitive_list.hpp"
#import <Foundation/Foundation.h>

@interface DBPrimitiveList ()

- (id)initWithCppPrimitiveList:(const ::PrimitiveList &)primitiveList;
- (::PrimitiveList)cppPrimitiveList;

@end
