// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#import <Foundation/Foundation.h>


@interface DBPrimitiveList : NSObject
- (id)initWithPrimitiveList:(DBPrimitiveList *)primitiveList;
- (id)initWithList:(NSMutableArray *)list;

@property (nonatomic, readonly) NSMutableArray *list;

@end
