// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#import <Foundation/Foundation.h>

@interface DBPrimitiveList : NSObject
- (nonnull instancetype)initWithList:(nonnull NSArray<NSNumber *> *)list;
+ (nonnull instancetype)primitiveListWithList:(nonnull NSArray<NSNumber *> *)list;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * list;

@end
