// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

#import <Foundation/Foundation.h>

@interface DBRecordWithDurationAndDerivings : NSObject
- (nonnull instancetype)initWithDt:(NSTimeInterval)dt;
+ (nonnull instancetype)recordWithDurationAndDerivingsWithDt:(NSTimeInterval)dt;

@property (nonatomic, readonly) NSTimeInterval dt;

- (NSComparisonResult)compare:(nonnull DBRecordWithDurationAndDerivings *)other;

@end
