// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum_flags.djinni

#import "DBRecordWithFlags.h"


@implementation DBRecordWithFlags

- (nonnull instancetype)initWithAccess:(DBAccessFlags)access
{
    if (self = [super init]) {
        _access = access;
    }
    return self;
}

+ (nonnull instancetype)recordWithFlagsWithAccess:(DBAccessFlags)access
{
    return [(DBRecordWithFlags*)[self alloc] initWithAccess:access];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p access:%@>", self.class, (void *)self, @(self.access)];
}

@end
