// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#import "DBRecordWithNestedDerivings.h"
#include "record_with_nested_derivings.hpp"
#import <Foundation/Foundation.h>

@interface DBRecordWithNestedDerivings ()

- (id)initWithCppRecordWithNestedDerivings:(const ::RecordWithNestedDerivings &)recordWithNestedDerivings;
- (::RecordWithNestedDerivings)cppRecordWithNestedDerivings;

@end
