// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#import <Foundation/Foundation.h>


@interface DBRecordWithDerivings : NSObject

@property (nonatomic, readonly) int32_t key1;

@property (nonatomic, readonly) NSString *key2;

- (NSComparisonResult)compare:(DBRecordWithDerivings *)other;

@end
