// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#import <Foundation/Foundation.h>

@interface DBRecordWithDerivings : NSObject
- (nonnull id)initWithRecordWithDerivings:(nonnull DBRecordWithDerivings *)recordWithDerivings;
- (nonnull id)initWithKey1:(int32_t)key1
                      key2:(nonnull NSString *)key2;

@property (nonatomic, readonly) int32_t key1;

@property (nonatomic, readonly, nonnull) NSString * key2;

- (NSComparisonResult)compare:(nonnull DBRecordWithDerivings *)other;

@end
