// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#import "DBRecordWithFlags.h"
#include "record_with_flags.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBRecordWithFlags;

namespace djinni_generated {

struct RecordWithFlags
{
    using CppType = ::testsuite::RecordWithFlags;
    using ObjcType = DBRecordWithFlags*;

    using Boxed = RecordWithFlags;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
