// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#include "second_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DBSecondListener;

namespace djinni_generated {

class SecondListener
{
public:
    using CppType = std::shared_ptr<::testsuite::SecondListener>;
    using CppOptType = std::shared_ptr<::testsuite::SecondListener>;
    using ObjcType = id<DBSecondListener>;

    using Boxed = SecondListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

