// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#import "DBSetRecord.h"


@implementation DBSetRecord

- (nonnull instancetype)initWithSet:(nonnull NSSet<NSString *> *)set
                               iset:(nonnull NSSet<NSNumber *> *)iset
{
    if (self = [super init]) {
        _set = [set copy];
        _iset = [iset copy];
    }
    return self;
}

+ (nonnull instancetype)setRecordWithSet:(nonnull NSSet<NSString *> *)set
                                    iset:(nonnull NSSet<NSNumber *> *)iset
{
    return [[self alloc] initWithSet:set
                                iset:iset];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p: dict, %@>", self.class, self, [[self toDict] description]];
}

- (NSDictionary *)toDict
{
    #define _djinni_hide_null_(_o_) ((_o_)?(_o_):([NSNull null]))
    
    return @{@"__class_name__": [self.class description], @"set": _djinni_hide_null_(self.set), @"iset": _djinni_hide_null_(self.iset)};
}

@end
