// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#import <Foundation/Foundation.h>


/** Used for ObjC multiple inheritance tests */
@protocol DBSecondListener

- (void)second;

@end
