// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#import "DBSetRecord.h"
#include "set_record.hpp"
#import <Foundation/Foundation.h>

@interface DBSetRecord ()

- (id)initWithCppSetRecord:(const ::djinni::cpp::SetRecord &)setRecord;
- (::djinni::cpp::SetRecord)cppSetRecord;

@end
