// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_inheritance.djinni

#import "DBSubCppInterfaceInheritance+Private.h"
#import "DBSubCppInterfaceInheritance.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DBSubCppInterfaceInheritance ()

- (id)initWithCpp:(const std::shared_ptr<::testsuite::SubCppInterfaceInheritance>&)cppRef;

@end

@implementation DBSubCppInterfaceInheritance {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::testsuite::SubCppInterfaceInheritance>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::testsuite::SubCppInterfaceInheritance>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (const std::shared_ptr<::testsuite::SubCppInterfaceInheritance>&) cppRef
{
    return _cppRefHandle.get();
}

// DBSubCppInterfaceInheritance methods

- (nonnull NSString *)subMethod {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->sub_method();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable DBSubCppInterfaceInheritance *)create {
    try {
        auto objcpp_result_ = ::testsuite::SubCppInterfaceInheritance::create();
        return ::djinni_generated::SubCppInterfaceInheritance::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

// DBBaseCppInterfaceInheritance methods

- (nonnull NSString *)baseMethod {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->base_method();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)overrideMethod {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->override_method();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SubCppInterfaceInheritance::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return [objc cppRef];
}

auto SubCppInterfaceInheritance::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DBSubCppInterfaceInheritance>(cpp);
}

}  // namespace djinni_generated

@end
