// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import "DBTestHelpers.h"
#include "test_helpers.hpp"
#import <Foundation/Foundation.h>
#include <memory>

@interface DBTestHelpers ()

@property (nonatomic, readonly) std::shared_ptr<TestHelpers> cppRef;

+ (id)testHelpersWithCpp:(const std::shared_ptr<TestHelpers> &)cppRef;

- (id)initWithCpp:(const std::shared_ptr<TestHelpers> &)cppRef;

@end
