// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import "DBClientInterface.h"
#import "DBColor.h"
#import <Foundation/Foundation.h>
@class DBMapListRecord;
@class DBNestedCollection;
@class DBPrimitiveList;
@class DBSetRecord;


@protocol DBTestHelpers

+ (DBSetRecord *)getSetRecord;

+ (BOOL)checkSetRecord:(DBSetRecord *)rec;

+ (DBPrimitiveList *)getPrimitiveList;

+ (BOOL)checkPrimitiveList:(DBPrimitiveList *)pl;

+ (DBNestedCollection *)getNestedCollection;

+ (BOOL)checkNestedCollection:(DBNestedCollection *)nc;

+ (NSMutableDictionary *)getMap;

+ (BOOL)checkMap:(NSMutableDictionary *)m;

+ (NSMutableDictionary *)getEmptyMap;

+ (BOOL)checkEmptyMap:(NSMutableDictionary *)m;

+ (DBMapListRecord *)getMapListRecord;

+ (BOOL)checkMapListRecord:(DBMapListRecord *)m;

+ (void)checkClientInterfaceAscii:(id <DBClientInterface>)i;

+ (void)checkClientInterfaceNonascii:(id <DBClientInterface>)i;

+ (void)checkEnumMap:(NSMutableDictionary *)m;

+ (NSNumber *)returnNone;

@end
