// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

#import <Foundation/Foundation.h>


@interface DBTestDuration : NSObject

+ (nonnull NSString *)hoursString:(NSTimeInterval)dt;

+ (nonnull NSString *)minutesString:(NSTimeInterval)dt;

+ (nonnull NSString *)secondsString:(NSTimeInterval)dt;

+ (nonnull NSString *)millisString:(NSTimeInterval)dt;

+ (nonnull NSString *)microsString:(NSTimeInterval)dt;

+ (nonnull NSString *)nanosString:(NSTimeInterval)dt;

+ (NSTimeInterval)hours:(int32_t)count;

+ (NSTimeInterval)minutes:(int32_t)count;

+ (NSTimeInterval)seconds:(int32_t)count;

+ (NSTimeInterval)millis:(int32_t)count;

+ (NSTimeInterval)micros:(int32_t)count;

+ (NSTimeInterval)nanos:(int32_t)count;

+ (NSTimeInterval)hoursf:(double)count;

+ (NSTimeInterval)minutesf:(double)count;

+ (NSTimeInterval)secondsf:(double)count;

+ (NSTimeInterval)millisf:(double)count;

+ (NSTimeInterval)microsf:(double)count;

+ (NSTimeInterval)nanosf:(double)count;

+ (nullable NSNumber *)box:(int64_t)count;

+ (int64_t)unbox:(nullable NSNumber *)dt;

@end
