// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import "DBTestHelpers.h"
#import "DBTestHelpersCppProxy.h"
#include "test_helpers.hpp"
#import "DJICppWrapperCache+Private.h"
#import <Foundation/Foundation.h>
#include <memory>

@interface DBTestHelpersCppProxy ()

@property (nonatomic, readonly) std::shared_ptr<::djinni::cpp::TestHelpers> cppRef;

+ (id)testHelpersWithCpp:(const std::shared_ptr<::djinni::cpp::TestHelpers> &)cppRef;

- (id)initWithCpp:(const std::shared_ptr<::djinni::cpp::TestHelpers> &)cppRef;

@end
