// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_token.djinni

#import <Foundation/Foundation.h>


@protocol DBUserToken <NSObject>

- (nonnull NSString *)whoami;

@end
