// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#import <Foundation/Foundation.h>
@class DBJavaOnlyListener;
@class DBPyOnlyListener;
@protocol DBObjcOnlyListener;


/**
 * Generating and compiling this makes sure other languages don't break
 * on references to interfaces they don't need.
 */
@protocol DBUsesSingleLanguageListeners

- (void)callForObjC:(nullable id<DBObjcOnlyListener>)l;

- (nullable id<DBObjcOnlyListener>)returnForObjC;

- (void)callForJava:(nullable DBJavaOnlyListener *)l;

- (void)callForPy:(nullable DBPyOnlyListener *)l;

- (nullable DBPyOnlyListener *)returnForPy;

@end
