// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#import "DBVarnameRecord.h"
#import <Foundation/Foundation.h>
@class DBVarnameInterface;


@interface DBVarnameInterface : NSObject

- (nonnull DBVarnameRecord *)Rmethod:(nonnull DBVarnameRecord *)RArg;

- (nullable DBVarnameInterface *)Imethod:(nullable DBVarnameInterface *)IArg;

@end
