// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#import "DBWcharTestRec.h"
#import <Foundation/Foundation.h>


@interface DBWcharTestHelpers : NSObject

+ (nonnull DBWcharTestRec *)getRecord;

+ (nonnull NSString *)getString;

+ (BOOL)checkString:(nonnull NSString *)str;

+ (BOOL)checkRecord:(nonnull DBWcharTestRec *)rec;

@end
